### PR TITLE
TINKERPOP-1120: If there is no view nor messages, don't create empty views/messages in SparkExecutor

### PR DESCRIPTION
**Pull request by okram**
https://issues.apache.org/jira/browse/TINKERPOP-1120

The following PR effects TraversalVertexProgram and SparkGraphComputer. Here is what changed in both:

	-------SparkGraphComputer
	1. If the vertex doesn't pass any messages, don't serialize an empty list, serialize null.
	2. If the vertex doesn't have a view, don't serialize an empty list of detached vertex properties, serialize null.
	3. If the vertex doesn't have a view nor messages, don't do anything!
	-------TraversalVertexProgram
	4. Found a memory bug where halted traversers were still distributed amongst the vertices even though they were sent to the master traversal.
	5. If a halted traverser TraverserSet is empty, remove the property (remove the vertex view!).

You can read about the performance gains by doing this here:
	https://groups.google.com/d/msg/gremlin-users/NKjEXdRNp-M/S48pDXjdAQAJ

CHANGELOG

```
* `SparkGraphComputer` no longer shuffles empty views or empty outgoing messages in order to save time and space.
* `TraversalVertexProgram` no longer maintains empty halted traverser properties in order to save space.
```

UPGRADE

```
TraversalVertexProgram
----------------------

`TraversalVertexProgram` always maintained a `HALTED_TRAVERSERS` `TraverserSet` for each vertex throughout the life of the OLAP computation. However, if there are no halted traversers in the set, then there is no point in keeping the compute property around as without it, time and space are saved. Users that have `VertexPrograms` that are chained off of `TraversalVertexProgram` that have previously assumed that `HALTED_TRAVERSERS` always exists, should now no longer assume that.

---java
// bad code
TraverserSet haltedTraversers = vertex.value(TraversalVertexProgram.HALTED_TRAVERSERS);
// good code
TraverserSet haltedTraversers = vertex.property(TraversalVertexProgram.HALTED_TRAVERSERS).orElse(new TraverserSet());
---
```

### CODE REVIEW

**Comment by okram** [comment]
VOTE +1 -- integration tests and Blade cluster benchmarking/testing.

**Comment by dkuppitz** [comment]
I see test failures.

```
Results :
Tests in error: 
  TinkerGraphStepStrategyTest>AbstractGremlinTest.setup:80 ? NullPointer
  TinkerGraphStepStrategyTest>AbstractGremlinTest.tearDown:135 ? NullPointer
Tests run: 2989, Failures: 0, Errors: 2, Skipped: 392
```

Tried twice, same result.

**Comment by okram** [comment]
@dkuppitz --- I can't seem to reproduce this. Note that there is nothing in this PR that has to do with the testing infrastructure (`AbstractGremlinTest`) or TinkerGraph (save indirectly via `TraversalVertexProgram`, but that wouldn't effect test setup and teardown infrastructure). Can you give line numbers to where the failure is occurring?

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Apache TinkerPop .................................. SUCCESS [5.301s]
[INFO] Apache TinkerPop :: Gremlin Shaded ................ SUCCESS [3.117s]
[INFO] Apache TinkerPop :: Gremlin Core .................. SUCCESS [42.045s]
[INFO] Apache TinkerPop :: Gremlin Test .................. SUCCESS [13.780s]
[INFO] Apache TinkerPop :: Gremlin Groovy ................ SUCCESS [43.143s]
[INFO] Apache TinkerPop :: Gremlin Groovy Test ........... SUCCESS [7.014s]
[INFO] Apache TinkerPop :: TinkerGraph Gremlin ........... SUCCESS [1:46.117s]
[INFO] Apache TinkerPop :: Gremlin Benchmark ............. SUCCESS [4.385s]
[INFO] Apache TinkerPop :: Hadoop Gremlin ................ SUCCESS [6:38.470s]
[INFO] Apache TinkerPop :: Spark Gremlin ................. SUCCESS [4:55.645s]
[INFO] Apache TinkerPop :: Giraph Gremlin ................ SUCCESS [6.477s]
[INFO] Apache TinkerPop :: Neo4j Gremlin ................. SUCCESS [3.377s]
[INFO] Apache TinkerPop :: Gremlin Driver ................ SUCCESS [8.600s]
[INFO] Apache TinkerPop :: Gremlin Server ................ SUCCESS [39.823s]
[INFO] Apache TinkerPop :: Gremlin Console ............... SUCCESS [17.190s]
[INFO] Apache TinkerPop :: Gremlin Archetype ............. SUCCESS [0.149s]
[INFO] Apache TinkerPop :: Archetype - TinkerGraph ....... SUCCESS [5.030s]
[INFO] Apache TinkerPop :: Archetype - Server ............ SUCCESS [10.586s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16:50.865s
[INFO] Finished at: Wed May 04 07:08:15 MDT 2016
[INFO] Final Memory: 133M/739M
[INFO] ------------------------------------------------------------------------
```

**Comment by okram** [comment]
Another thing that is weird. `TinkerGraphStepStrategyTest` doesn't even use `TraversalVertexProgram` and thus, this failure is in no way related to the changed in this PR.

```
 @IgnoreEngine(COMPUTER)
    public void shouldFoldInHasContainers() {
```

**Comment by dkuppitz** [comment]
That's the full log of the 2nd time it failed: https://gist.github.com/dkuppitz/406e2e89dc10b74aeaef9a11c4bb7718

**Comment by dkuppitz** [comment]
Build worked properly on the other machine.

VOTE: +1

**Comment by okram** [comment]
That is a wierd `NullPointerException` in that the `graphProvider` of the test is null.

```
        graphProvider = GraphManager.getGraphProvider(); // THIS BECOMES NULL ?
        graphProvider.getTestListener().ifPresent(l -> l.onTestStart(this.getClass(), name.getMethodName()));
```

What is different about your other machine?

**Comment by dkuppitz** [comment]
My other machine is my my usual dev machine. I was trying to optimize things by running full test suites on OpenStack CoreOS instances, that failed. I will try that again using a different OS.

**Comment by spmallette** [comment]
VOTE +1 - tested with `mvn clean install`

**Pull request merged**
