### PR TITLE
TINKERPOP-575 RemoteGraph

### PR DESCRIPTION
**Pull request by spmallette**
https://issues.apache.org/jira/browse/TINKERPOP-575

This is a brute of a PR that introduces `RemoteGraph`. The tests execute as part of gremlin-server with regular old `mvn clean install`. There's lots of optimizations and improvements we could make all around, but we at least have something fully functional at this point with this PR.

Docs generate nice...you can find the `RemoteGraph` docs here:

http://tinkerpop.apache.org/docs/3.2.0-SNAPSHOT/reference/#connecting-via-remotegraph

The upgrade docs are here:

http://tinkerpop.apache.org/docs/3.2.0-SNAPSHOT/upgrade/#_remotegraph

The developer/provider docs are here:

http://tinkerpop.apache.org/docs/3.2.0-SNAPSHOT/dev/provider/#remoteconnection-implementations

VOTE +1 - phew!

### CODE REVIEW

**Comment by dkuppitz** [comment]
Wonderful!

VOTE: +1

**Comment by okram** [comment]
The insane PR. VOTE +1.

**Comment by mpollmeier** [comment]
Awesome to see progress on this! I had some trouble getting it to work though. Here's what I id:

build it
```
git checkout TINKERPOP-575 #currently e01a71b
mvn clean install -DskipTests
```

start gremlin-server
```
unzip $TP_SRC/gremlin-server/target/apache-gremlin-server-3.2.0-SNAPSHOT-distribution.zip
cd apache-gremlin-server-3.2.0-SNAPSHOT 
bin/gremlin-server.sh conf/gremlin-server-modern.yaml
```

connect and run traversal
```
cd gremlin-console/target/apache-gremlin-console-3.2.0-SNAPSHOT-standalone
bin/gremlin.sh
         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
plugin activated: tinkerpop.server
plugin activated: tinkerpop.utilities
plugin activated: tinkerpop.tinkergraph
gremlin> graph = RemoteGraph.open('conf/remote-graph.properties')
==>remotegraph[DriverServerConnection-localhost/127.0.0.1:8182 [graph='graph]]
gremlin> g = graph.traversal()
==>graphtraversalsource[remotegraph[DriverServerConnection-localhost/127.0.0.1:8182 [graph='graph]], standard]
gremlin> g.V().valueMap(true)
```

No output :(
PS1: works fine for local TinkerGraph instance
PS2: Wireshark tells me that there is some communication between the REPL and gremlin-server (three TCP packets).

**Comment by spmallette** [comment]
@mpollmeier that was a nice bug find. i never unpackaged the zip and my assembly files had a bug in them. the `scripts` directory wasn't being included so the graph couldn't get initialized with data which so you were executing your remotes against an empty graph and getting no results.  Should work for you now if you try again. Reviewing the distributions now to be sure nothing else is amiss.

**Comment by mpollmeier** [comment]
works fine now, thanks!

**Pull request merged**
