### PR TITLE
TINKERPOP-1318: use mockito-core instead of mockito-all to avoid hamcrest conflict

### PR DESCRIPTION
**Pull request by pluradj**
https://issues.apache.org/jira/browse/TINKERPOP-1318

### CODE REVIEW

**Comment by okram** [comment]
Do integration tests pass? ... that will be all I care about. @spmallette will have deeper thoughts on the matter as he uses Mockito.

**Comment by pluradj** [comment]
Yes, I ran integration tests with `-DincludeNeo4j`

**Comment by okram** [comment]
VOTE +1.

**Comment by PommeVerte** [comment]
This change is simple enough and shouldn't impact anything (short of an incompatibility between mockito and the version of hamcrest here, but the tests pass so it should be ok.)

VOTE +1

**Comment by pluradj** [comment]
VOTE: +1

**Pull request merged**
