### PR TITLE
TINKERPOP-1199:Use "MicroMetrics" as the mutator of the TraversalMetrics.

### PR DESCRIPTION
**Pull request by rjbriody**
https://issues.apache.org/jira/browse/TINKERPOP-1199

Eliminate iteration-time connection between profiling Metrics.
Move upstream duration calculation to finalization of Traversal.

### CODE REVIEW

**Comment by okram** [comment]
This has been merged to a local `TINKERPOP-1199` branch as more work still needs to be done. Will put up for VOTE via a PR from the local branch after @rjbriody and I get this all squared away.

**Comment by okram** [comment]
This is ready to VOTE. The completed branch is actually TINKERPOP-1199 locally (not in @rjbriody's repository anymore). I can't seem to make a PR from that our local branch as doing so just links me to this ticket. Don't know how that effects VOTERs and their testing ? --- just be aware.

In short, profiling and the new sideEffect/memory model of GraphComputer have been reconciled. This was painful as profiling is a very complicated/intrusive system. However, getting it to work with the new memory-model in OLAP is a strong testament to the flexibility of the changes forthcoming in 3.2.0 OLAP. Bob and I added lots more testing as well. Also, there was a severe bug found in `ComputerVerificationStrategy` that has since been rectified (a profile test exposed it).

CHANGELOG

```
* Fixed a bug around profiling and nested traversals.
```

VOTE +1.

**Comment by okram** [comment]
Here is the complete branch: https://github.com/apache/incubator-tinkerpop/tree/TINKERPOP-1199

**Comment by PommeVerte** [comment]
Cool work guys. This makes a lot of sense functionally. It's a nice bonus that you caught that issue in the middle of it.
 VOTE +1

**Comment by twilmes** [comment]
Looks good, VOTE +1

**Pull request merged**
