### PR TITLE
TINKERPOP-1236: SelectDenormalizationStrategy for select().by(starGraph) in OLAP.

### PR DESCRIPTION
**Pull request by okram**
https://issues.apache.org/jira/browse/TINKERPOP-1236

This is massive. We have been plagued by `select("a","b").by("name").by("age")`-style traversals not working in OLAP because they are `PathProcessor` traversals are grab `ReferenceElements` out of the `LABELED_PATH`. However, you can compile these to work:

```
select("a").by("name") -> select("a").map(values("name"))
select("a","b").by("name").by("age") -> select("a").map(values("name")).as("a").select("b").map(values("name")).as("b").select(last,"a","b")
```

When we are able to drop path labels, we will be able to open up `where(as("a").outE().count().is(gt(10))`-style traversals to OLAP as well. Note that this type of `WhereTraversalStep` typically is used in conjunction with `MatchStep` and `MatchPredicateStrategy` handles it appropriately so we are not missing out too much.

CHANGELOG

```
* `select("a","b").by("name").by("age")`-style traversals now work in OLAP with new  `PathProcessorStrategy`.
```

### CODE REVIEW

**Comment by okram** [comment]
`mvn clean install` 
VOTE +1.  
  (Giraph integration will not be effected by this if SparkGraphComputer tests pass -- which they do).

**Comment by okram** [comment]
Sorry. Pushed something that should have gone into `master/` around `GraphFilter` exceptions. Anywho, if this PR gets merged into `master/`, all is good.

**Comment by okram** [comment]
This is a failure from another PR that wasn't full integration tested. This is not related to this PR.

```
shouldSerializeTree(org.apache.tinkerpop.gremlin.structure.SerializationTest$GraphSONTest)  Time elapsed: 0.206 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.apache.tinkerpop.gremlin.structure.SerializationTest$GraphSONTest.shouldSerializeTree(SerializationTest.java:385)

Running org.apache.tinkerpop.gremlin.neo4j.structure.NoMultiNoMetaNeo4jGraphStructureStandardTest
Tests run: 799, Failures: 1, Errors: 0, Skipped: 266, Time elapsed: 216.4 sec <<< FAILURE! - in org.apache.tinkerpop.gremlin.neo4j.structure.NoMultiNoMetaNeo4jGraphStructureStandardTest
shouldSerializeTree(org.apache.tinkerpop.gremlin.structure.SerializationTest$GraphSONTest)  Time elapsed: 0.152 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.apache.tinkerpop.gremlin.structure.SerializationTest$GraphSONTest.shouldSerializeTree(SerializationTest.java:385)


Results :

Failed tests:
  SerializationTest$GraphSONTest.shouldSerializeTree:385 expected:<1> but was:<0>
  SerializationTest$GraphSONTest.shouldSerializeTree:385 expected:<1> but was:<0>
```

**Comment by twilmes** [comment]
Strategy application code looks and new select traversals look to cover the different permutations that will require expansion into map steps by the new strategy.

VOTE: +1

**Comment by dkuppitz** [comment]
VOTE: +1

**Pull request merged**
