### PR TITLE
TINKERPOP-1231: Get RemoteGraph to work with GraphComputer traversals (OLAP).

### PR DESCRIPTION
**Pull request by okram**
https://issues.apache.org/jira/browse/TINKERPOP-1231

I got `RemoteGraph` to work with `GraphComputer` OLAP traversals. I had to tweak a few things in `RemoteGraphProvider` and `GremlinRunner` that I didn't like doing. @spmallette -- It would be great if `RemoteException` was able to provide `getCause()`. I started going down that road, but got scared as it touched too many things -- `RemoteMessage`, `RemoteConnectionException`, etc....

### CODE REVIEW

**Comment by twilmes** [comment]
Nice addition to the remote graph functionality.  Code looks good. 

VOTE +1

**Comment by okram** [comment]
@twilmes --- While we can merge at this time, there is some things I would like @spmallette to look at. He will most likely add a commit.

**Comment by spmallette** [comment]
This is cool - I will have to think about how to serialize back specific exceptions. There's room in the protocol for that if I recall correctly.  The trick is that I'd be only able to send back standard Java exceptions i guess as sending back others might put the client in a position where it can't deserialize the exception if the exception class is only on the server but not the client.

**Comment by okram** [comment]
VOTE +1. Docs build and published as well. http://tinkerpop.apache.org/docs/3.2.0-SNAPSHOT/reference/

**Comment by okram** [comment]
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Apache TinkerPop .................................. SUCCESS [5.002s]
[INFO] Apache TinkerPop :: Gremlin Shaded ................ SUCCESS [2.351s]
[INFO] Apache TinkerPop :: Gremlin Core .................. SUCCESS [40.818s]
[INFO] Apache TinkerPop :: Gremlin Test .................. SUCCESS [11.800s]
[INFO] Apache TinkerPop :: Gremlin Groovy ................ SUCCESS [42.908s]
[INFO] Apache TinkerPop :: Gremlin Groovy Test ........... SUCCESS [7.821s]
[INFO] Apache TinkerPop :: TinkerGraph Gremlin ........... SUCCESS [3:29.036s]
[INFO] Apache TinkerPop :: Hadoop Gremlin ................ SUCCESS [5:34.840s]
[INFO] Apache TinkerPop :: Spark Gremlin ................. SUCCESS [7:11.440s]
[INFO] Apache TinkerPop :: Giraph Gremlin ................ SUCCESS [2:31:37.934s]
[INFO] Apache TinkerPop :: Neo4j Gremlin ................. SUCCESS [17:59.766s]
[INFO] Apache TinkerPop :: Gremlin Driver ................ SUCCESS [10.125s]
[INFO] Apache TinkerPop :: Gremlin Server ................ SUCCESS [12:48.995s]
[INFO] Apache TinkerPop :: Gremlin Console ............... SUCCESS [1:25.231s]
[INFO] Apache TinkerPop :: Gremlin Archetype ............. SUCCESS [0.085s]
[INFO] Apache TinkerPop :: Archetype - TinkerGraph ....... SUCCESS [6.298s]
[INFO] Apache TinkerPop :: Archetype - Server ............ SUCCESS [10.648s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3:22:25.665s
[INFO] Finished at: Wed Mar 23 22:11:36 MDT 2016
[INFO] Final Memory: 97M/814M
[INFO] ------------------------------------------------------------------------
```

**Comment by spmallette** [comment]
Paired with marko on this yesterday - good stuff: VOTE +1

**Pull request merged**
