### PR TITLE
TINKERPOP-937 Extracted "provider docs" to their own book.

### PR DESCRIPTION
**Pull request by spmallette**
https://issues.apache.org/jira/browse/TINKERPOP-937

Moved from the standard reference documentation.  Added links between the docs where necessary. Published docs for review here:

http://tinkerpop.apache.org/docs/3.1.2-SNAPSHOT/dev/provider/

VOTE +1

### CODE REVIEW

**Comment by spmallette** [comment]
@velo watching the appveyor build. looks like we got a clean one on the branch but a failed one on the pr...maybe just a fluke with hadoop? thought you might want to look at the logs....

if anyone is reviewing this, i wouldn't worry about the single appveyor failure - the other three builds were good.

**Comment by velo** [comment]
Should be a race/timing issue...
```
Failed tests: 
  GroovyProfileTest$Traversals>ProfileTest.g_V_sideEffectXThread_sleepX10XX_sideEffectXThread_sleepX5XX_profile:173 Duration should be at least the length of the sleep (59ms): 53 
 
Tests run: 1722, Failures: 1, Errors: 0, Skipped: 821
```

**Comment by pluradj** [comment]
VOTE +1

**Comment by okram** [comment]
VOTE +1.

**Pull request merged**
