### PR TITLE
TINKERPOP-1153 & TINKERPOP-1154: (Summary) Multi-OLAP compilation in a single Traversal (hardened)

### PR DESCRIPTION
**Pull request by okram**
https://issues.apache.org/jira/browse/TINKERPOP-1154
https://issues.apache.org/jira/browse/TINKERPOP-1153

There is a lot in this pull request. While creating the infrastructure to allow us to do multi-OLAP jobs in a single Traversal compilation, I ended up cleaning numerous ancient areas of the codebase that were awkward with respects to latest developments. Everything is backwards compatible though there are lots of Deprecations. However, there is a new `GraphComptuerTest` that requires that `GraphComputer` providers support "compute key revival." I had to do a small tweak to both `TinkerGraphComputer` and `SparkGraphComputer` for them to pass the test. `GiraphGraphComputer` just handled it. For users, this ticket basically provides them:

```
g.V().hasLabel('person').
  pageRank(0.85).
    by('friendRank').
    by(outE('knows')).
    times(10).
  out('worksFor').order().by('friendRank').limit(10).valueMap('name','friendRank')
```

CHANGELOG

```
* Added `PeerPressureVertexProgramStep` and `GraphTraversal.peerPressure()`.
* Added `PureTraversal` for handling pure and compiled versions of a `Traversal`. Useful in OLAP.
* Added `ScriptTraversal` which allows for delayed compilation of script-based `Traversals`.
* Simplified `VertexProgram` implementations with a `PureTraversal`-model and deprecated `ConfigurationTraversal`.
* Simplified script-based `Traversals` via `ScriptTraversal` and deprecated `TraversalScriptFunction` and `TraversalScriptHelper`.
* Added `ByModulating` interface which allows the `Step` to decide how a `by()`-modulation should be handled. (*breaking*)
* Simplified the `by()`-modulation patterns of `OrderGlobalStep` and `OrderLocalStep`.
* Added `GraphComputerTest.shouldSupportPreExistingComputeKeys()` to ensure existing compute keys are "revived." (*breaking*)
```

UPDATE DOCS

```
For providers that support their own `GraphComputer` implementation, note that there is a new `GraphComputerTest.shouldSupportPreExistingComputeKeys()`. When chaining OLAP jobs together, if an OLAP job requires the compute keys of a previous OLAP job, then the existing compute keys must be accessible. A simple 2 line change to `SparkGraphComputer` and `TinkerGraphComputer` solved this for TinkerPop. `GiraphGraphComputer` did not need an update as this feature was already naturally supported.

If the provider has custom steps that leverage `by()`-modulation, those still will now need to implement `ByModulating`. Most of the methods in `ByModulating` are `default` and, for most situations, only `ByModulating.modulateBy(Traversal)` should be implemented. Note that this method's body will most like be identical to `TraversalParent.addLocalChild()`.

Providers that have custom Gremlin language implementations (e.g. Gremlin-Scala), there is a new class called `ScriptTraversal` which will handle script-based processing of traversals. The entire `GroovyXXXTest`-suite was updated to use this new class. The previous `TraversalScriptHelper` class has been deprecated so immediate upgrading is not required.
```

REFERENCE DOCS

*** I will do these at the time of merge.

### CODE REVIEW

**Comment by okram** [comment]
I decided to write the docs. Docs written. Note that they don't build. This has nothing to do with this PR. It has to do with the recent fix to the `manifest` for Neo4j plugin. Neo4j pulls in Scala 2.11.x while Spark uses 2.10.x. The doc builder (having all plugins installed at once) makes it so Spark uses Scala 2.11.x and there are "NoMethodDefinedExceptions." This effects `tp31` branch, but not `master/` as master will (in a later ticket) bump to Spark 1.6.0 which uses Scala 2.11.x.

**Comment by okram** [comment]
VOTE +1.

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Apache TinkerPop .................................. SUCCESS [5.044s]
[INFO] Apache TinkerPop :: Gremlin Shaded ................ SUCCESS [2.132s]
[INFO] Apache TinkerPop :: Gremlin Core .................. SUCCESS [38.711s]
[INFO] Apache TinkerPop :: Gremlin Test .................. SUCCESS [12.019s]
[INFO] Apache TinkerPop :: Gremlin Groovy ................ SUCCESS [32.419s]
[INFO] Apache TinkerPop :: Gremlin Groovy Test ........... SUCCESS [6.354s]
[INFO] Apache TinkerPop :: TinkerGraph Gremlin ........... SUCCESS [3:27.877s]
[INFO] Apache TinkerPop :: Hadoop Gremlin ................ SUCCESS [5:07.110s]
[INFO] Apache TinkerPop :: Spark Gremlin ................. SUCCESS [10:39.819s]
[INFO] Apache TinkerPop :: Giraph Gremlin ................ SUCCESS [2:21:44.149s]
[INFO] Apache TinkerPop :: Neo4j Gremlin ................. SUCCESS [17:29.014s]
[INFO] Apache TinkerPop :: Gremlin Driver ................ SUCCESS [8.910s]
[INFO] Apache TinkerPop :: Gremlin Server ................ SUCCESS [10:56.703s]
[INFO] Apache TinkerPop :: Gremlin Console ............... SUCCESS [1:08.703s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3:12:19.462s
[INFO] Finished at: Wed Feb 17 19:59:19 MST 2016
[INFO] Final Memory: 93M/731M
[INFO] ------------------------------------------------------------------------
~/software/tinkerpop/tinkerpop3$
```

**Comment by dkuppitz** [comment]
```
Failed tests: 
  PageRankTest$Traversals>PageRankTest.g_V_hasLabelXsoftwareX_hasXname_rippleX_pageRankX1X_byXinEXcreatedXX_timesX1X_byXpriorsX_inXcreatedX_unionXboth__identityX_valueMapXname_priorsX:176 expected:<1.0> but was:<0.0>
```

**Comment by okram** [comment]
@dkuppitz ... that is weird. It all finished for me just now. Can you run the query in the console and tell me what you get:

```
g.V().hasLabel("software").has("name", "ripple").pageRank(1.0).by(__.inE("created")).times(1).by("priors").in("created").union(__.both(), __.identity()).valueMap("name", "priors")
```


```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Apache TinkerPop .................................. SUCCESS [4.355s]
[INFO] Apache TinkerPop :: Gremlin Shaded ................ SUCCESS [3.344s]
[INFO] Apache TinkerPop :: Gremlin Core .................. SUCCESS [38.227s]
[INFO] Apache TinkerPop :: Gremlin Test .................. SUCCESS [11.285s]
[INFO] Apache TinkerPop :: Gremlin Groovy ................ SUCCESS [32.956s]
[INFO] Apache TinkerPop :: Gremlin Groovy Test ........... SUCCESS [6.191s]
[INFO] Apache TinkerPop :: TinkerGraph Gremlin ........... SUCCESS [3:16.894s]
[INFO] Apache TinkerPop :: Hadoop Gremlin ................ SUCCESS [5:01.567s]
[INFO] Apache TinkerPop :: Spark Gremlin ................. SUCCESS [10:15.725s]
[INFO] Apache TinkerPop :: Giraph Gremlin ................ SUCCESS [2:24:31.663s]
[INFO] Apache TinkerPop :: Neo4j Gremlin ................. SUCCESS [17:33.444s]
[INFO] Apache TinkerPop :: Gremlin Driver ................ SUCCESS [9.075s]
[INFO] Apache TinkerPop :: Gremlin Server ................ SUCCESS [10:55.872s]
[INFO] Apache TinkerPop :: Gremlin Console ............... SUCCESS [1:08.465s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3:14:29.536s
[INFO] Finished at: Thu Feb 18 17:46:39 MST 2016
[INFO] Final Memory: 95M/707M
[INFO] ------------------------------------------------------------------------
```

**Comment by spmallette** [comment]
looks like travis shows the same error as what @dkuppitz got

**Comment by okram** [comment]
So weird. Again, overnight.

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Apache TinkerPop .................................. SUCCESS [5.222s]
[INFO] Apache TinkerPop :: Gremlin Shaded ................ SUCCESS [2.530s]
[INFO] Apache TinkerPop :: Gremlin Core .................. SUCCESS [38.401s]
[INFO] Apache TinkerPop :: Gremlin Test .................. SUCCESS [11.325s]
[INFO] Apache TinkerPop :: Gremlin Groovy ................ SUCCESS [32.358s]
[INFO] Apache TinkerPop :: Gremlin Groovy Test ........... SUCCESS [6.013s]
[INFO] Apache TinkerPop :: TinkerGraph Gremlin ........... SUCCESS [3:15.039s]
[INFO] Apache TinkerPop :: Hadoop Gremlin ................ SUCCESS [5:03.753s]
[INFO] Apache TinkerPop :: Spark Gremlin ................. SUCCESS [10:01.122s]
[INFO] Apache TinkerPop :: Giraph Gremlin ................ SUCCESS [2:24:33.823s]
[INFO] Apache TinkerPop :: Neo4j Gremlin ................. SUCCESS [17:40.001s]
[INFO] Apache TinkerPop :: Gremlin Driver ................ SUCCESS [8.919s]
[INFO] Apache TinkerPop :: Gremlin Server ................ SUCCESS [10:56.373s]
[INFO] Apache TinkerPop :: Gremlin Console ............... SUCCESS [1:08.209s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3:14:23.560s
[INFO] Finished at: Thu Feb 18 21:43:01 MST 2016
[INFO] Final Memory: 94M/708M
[INFO] ------------------------------------------------------------------------
```

Here I will just comment out that test. If you guys can tell me what result of the query is in the console I can fix it later, but without it failing here, I have no idea.

**Comment by okram** [comment]
Here is what I get in the console for that query:

```
gremlin> g = TinkerFactory.createModern().traversal().withComputer()
==>graphtraversalsource[tinkergraph[vertices:6 edges:6], tinkergraphcomputer]
gremlin> g.V().hasLabel("software").has("name", "ripple").pageRank(1.0).by(__.inE("created")).times(1).by("priors").in("created").union(__.both(), __.identity()).valueMap("name", "priors")
==>[name:[marko], priors:[0.0]]
==>[name:[lop], priors:[0.0]]
==>[name:[josh], priors:[1.0]]
==>[name:[ripple], priors:[0.0]]
gremlin>
```

If someone who has a fail can tell me what they get that would help. However, again, I just commented out the test for now so I don't waste a day sitting here on an inanity.

**Comment by dkuppitz** [comment]
The error was only [reported by Travis](https://travis-ci.org/apache/incubator-tinkerpop/builds/110233907). I can't reproduce it on my local machine. I ran that particular query a few thousand times to see if this is going to be another random error, but the result seems to be consistent.

* `mvn clean install`: passed
* integration tests: passed

I looked roughly over the code; looks good, but it's hard to grasp all the changes in 120 files, I could spend a whole day on it, hence ...

VOTE: +0.5 (just to get at least one more reviewer for this PR)

```
[INFO] Reactor Summary:
[INFO] 
[INFO] Apache TinkerPop .................................. SUCCESS [10.549s]
[INFO] Apache TinkerPop :: Gremlin Shaded ................ SUCCESS [5.610s]
[INFO] Apache TinkerPop :: Gremlin Core .................. SUCCESS [1:05.941s]
[INFO] Apache TinkerPop :: Gremlin Test .................. SUCCESS [18.247s]
[INFO] Apache TinkerPop :: Gremlin Groovy ................ SUCCESS [59.668s]
[INFO] Apache TinkerPop :: Gremlin Groovy Test ........... SUCCESS [14.663s]
[INFO] Apache TinkerPop :: TinkerGraph Gremlin ........... SUCCESS [9:36.751s]
[INFO] Apache TinkerPop :: Hadoop Gremlin ................ SUCCESS [12:24.137s]
[INFO] Apache TinkerPop :: Spark Gremlin ................. SUCCESS [26:11.246s]
[INFO] Apache TinkerPop :: Giraph Gremlin ................ SUCCESS [2:59:20.410s]
[INFO] Apache TinkerPop :: Neo4j Gremlin ................. SUCCESS [11.686s]
[INFO] Apache TinkerPop :: Gremlin Driver ................ SUCCESS [28.561s]
[INFO] Apache TinkerPop :: Gremlin Server ................ SUCCESS [12:02.678s]
[INFO] Apache TinkerPop :: Gremlin Console ............... SUCCESS [1:56.698s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4:05:07.482s
[INFO] Finished at: Fri Feb 19 16:56:42 CET 2016
[INFO] Final Memory: 62M/688M
[INFO] ------------------------------------------------------------------------
```

^^ That's for the previous version (before you excluded the test).

**Comment by twilmes** [comment]
Reproduced the failure b/f your last push on my linux box and that it was fixed after a pull.  Looks good.

VOTE +1

**Comment by spmallette** [comment]
All good from me at this point - I'm good after the fix:

VOTE +1

**Comment by okram** [comment]
Dope. I guess code reviews are important..........NOT.

**Pull request merged**
