### PR TITLE
use the GraphProvider to convert hardcoded ids

### PR DESCRIPTION
**Pull request by pietermartin**
The hardcoded integer ids fail on providers that do not have integer ids.

### CODE REVIEW

**Comment by pietermartin** [comment]
This references TINKERPOP3-1001

**Comment by okram** [comment]
@pietermartin -- sorry to be picky, but can you make it be:

```
g.V(convertToVertexId("marko")).blah().blah()
```

instead of the direct reference to the `graphProvider` ? Or, if you want, upon merge, I can convert accordingly.

**Comment by pietermartin** [comment]
@okram Done.

**Comment by okram** [comment]
I ran `mvn clean install` and all passed. This is a trivial fix so I'm just going to CTR merge it.

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11:32.775s
[INFO] Finished at: Mon Nov 30 13:55:37 MST 2015
[INFO] Final Memory: 112M/788M
[INFO] ------------------------------------------------------------------------
~/software/tinkerpop/tinkerpop3$
```

**Pull request merged**
