### PR TITLE
When hosts configured incorrectly, causing problems not connect services

### PR DESCRIPTION
**Pull request by okuc**
Mainly to solve the following problem:

I have two machines, machine name and ip as follows:

```
           ip                             hostname
192.168.1.1                         host11
192.168.1.2                         host12

```
I start gremlin-server on 192.168.1.1, and then access on 192.168.1.2.

But for some reason, the hosts file on the 192.168.1.2 is not configured correctly, as follows:

`192.168.1.1 host33`

So I'm on the 192.168.1.2, it will report an error when accessing the gremlin-server. My statement is as follows access

```
  Builder builder = Cluster.build ( "192.168.1.1");
  Cluster cluster = builder.create ();
  Client client = cluster.connect ();
  ResultSet results = client.submit ( "[1,2,3,4]");
  results.stream () forEach (System.out :: println).;
```
It reported the following error:

```
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.TimeoutException: Timed out waiting for an available host.
at org.apache.tinkerpop.gremlin.driver.Client.submit (Client.java:146)
at org.apache.tinkerpop.gremlin.driver.Client.submit (Client.java:130)
at com.okuc.graph.hello.remote.main (remote.java:27)
Caused by: java.lang.RuntimeException: java.util.concurrent.TimeoutException: Timed out waiting for an available host.
at org.apache.tinkerpop.gremlin.driver.Client.submitAsync (Client.java:194)
at org.apache.tinkerpop.gremlin.driver.Client.submitAsync (Client.java:174)
at org.apache.tinkerpop.gremlin.driver.Client.submit (Client.java:144)
... 2 more
Caused by: java.util.concurrent.TimeoutException: Timed out waiting for an available host.
at org.apache.tinkerpop.gremlin.driver.Client $ ClusteredClient.chooseConnection (Client.java:342)
at org.apache.tinkerpop.gremlin.driver.Client.submitAsync (Client.java:189)
... 4 more
```

### CODE REVIEW

**Comment by spmallette** [comment]
i think there's something wrong with this PR - see the commits?

**Comment by okuc** [comment]
I'm very sorry for it, I do not know why it is like this, I was a novice. I merely note ‘Files changed’ is correct. Could you tell me, I might be doing something wrong there，thank you?

**Comment by spmallette** [comment]
looks like you merged 'master' into 'tp31 as part of this.....see the last commit listed - maybe that's what this is.

**Comment by okuc** [comment]
Yes, you are right. I really did.
 You let me in [#257](https://github.com/apache/incubator-tinkerpop/pull/257) re-submitted to the tp31 branch, so I merged  master branch  into thetp31 branch, and then submitted.

 Now how can I do, how to restore this error?

 In addition, I would like to know, is the right way how to do it?

Very sorry to bother you.

**Comment by spmallette** [comment]
in this specific case of "retargeting to tp31" you should have just probably cherrypicked your commit from your master to your tp31 branch and then re-issued your pull request to our tp31. undoing this mess is beyond the scope of what i can offer as help here, but merging master into tp31 is the exact opposite direction our merge flows goes.  

The "right way" to offer PRs to TinkerPop is to first create an issue in JIRA:

https://issues.apache.org/jira/browse/TINKERPOP/

It is in there or through discussion on the dev mailing list that you can communicate with core developers on the project about which branch it should target. Then  you should likely create a branch in your fork from the TinkerPop branch you intend to target and do your work in there.  Finally, issue your PR and await review. More information on this process is outlined in the developer docs:

http://tinkerpop.apache.org/docs/3.1.1-incubating/dev/developer/#_contributing

**Comment by okuc** [comment]
I have re-checked out branch tp31, and modify the good. But I can not use the following command "mvn clean install && mvn verify -pl gremlin-server -DskipIntegrationTests" package through, so it is not submitted, would like to ask, tp31 branch can not compile package, it is normal?

**Comment by spmallette** [comment]
are you asking why you can't do `mvn package`? i think it has something to do with `gremlin-shaded` which binds to later maven events to properly work.

**Comment by okuc** [comment]
I mean, I use the following command, always build unsuccessful：

`mvn clean install && mvn verify -pl gremlin-server -DskipIntegrationTests`


errors：

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project gremlin-server: Compilation failure: Compilation failure:
[ERROR] /D:/MyGit/incubator-tinkerpop/gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/auth/SimpleAuthenticator.java:[27,19] 程序包org.mindrot不存在
[ERROR] /D:/MyGit/incubator-tinkerpop/gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/auth/SimpleAuthenticator.java:[141,14] 找不到符号
[ERROR] 符号:   变量 BCrypt
[ERROR] 位置: 类 org.apache.tinkerpop.gremlin.server.auth.SimpleAuthenticator
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

Is this project not compiled in win10?  or
I still have not configured the environment variables?

**Comment by spmallette** [comment]
I don't know - as far as i know `mvn clean install` should work at a minimum. Try the running the windows profile maybe:

https://github.com/apache/incubator-tinkerpop/blob/58f912b1199cb5ee99c3a45f28343c01a19312da/pom.xml#L1039-L1077

Note that even that is not perfect. A fully functioning windows build is still under development. If you can help there that would be great: #244

**Comment by spmallette** [comment]
@okuc do you plan to return to correct this pull request? or can we close it? I'm still not completely following what you intended to fix here and without knowing if all the tests work, it is hard for me to properly evaluate this work.

**Comment by spmallette** [comment]
I've just closed this as there has been no activity on it in several weeks and as stated earlier, I can't really ascertain the nature of this PR in the state it is in now.

**Pull request closed without merging**
