### PR TITLE
Update Maven plugins (mostly minor version updates)

### PR DESCRIPTION
**Pull request by ceefour**

### CODE REVIEW

**Comment by spmallette** [comment]
I see you changed the `asciidoctor-maven-plugin` version - that's a pretty major version change - did you build the documentation with `bin/process-docs.sh` to be sure that it works and everything still looks good?

**Comment by ceefour** [comment]
@spmallette I've left asciidoctor as before. I'll make another pull request just for asciidoctor when I've verified asciidoctor `process-docs.sh` working.

**Comment by okram** [comment]
VOTE +1.

**Comment by spmallette** [comment]
Did some basic tests that all seemed to look ok after this change:

* `mvn clean install`
* ran integration tests for gremlin server
* `process-docs.sh` worked but only after i reverted to hadoop 2.7.1 (that may be an open issue still  from #262 - @okram  you may want to review that again )
* tried out the distributions that were created ever so lightly

@ceefour i have to be honest. i don't like to arbitrarily bump versions of things without reasons. TinkerPop has been burned on that so many times before where pull requests like this one were merged and we ended up with surprises on release day......and as I'm typically the release manager these days, i don't want surprises :wink: 

were you actually trying to fix something here with these changes? did you look at the release notes of each of these projects to see what these new releases are providing to us? bug fixes? features? can you provide some synopsis of what those are?

**Comment by spmallette** [comment]
Taking back what I said about not being able to generate docs on 2.7.2 - just got it to work. other issues/questions i posed still stand.

**Comment by spmallette** [comment]
@ceefour please have a look at my last couple of comments as i still have open questions about this PR. until then my VOTE is -1 and we should probably just close this.  thanks.

**Comment by ceefour** [comment]
Okay.. not fixing a non-broken thing.. :)

**Pull request closed without merging**
