### PR TITLE
TINKERPOP-971: TraversalSource should be fluent like GraphComputer

### PR DESCRIPTION
**Pull request by okram**
https://issues.apache.org/jira/browse/TINKERPOP-971

The concept of a `TraversalSource` is now very explicit and used extensively. Any traversal is composed of both a `TraversalSource` and a `Traversal`. Prior to this PR, `TraversalSources` were manipulated via a very awkward/error prone "builder model." Moreover, there were objects that didn't need to exist -- e.g. `TraversalEngine`. With this PR, the API now looks like this:

```
g = graph.traversal().withCompute(SparkGraphComputer.class).withStrategies(ReadOnlyStrategy.instance())
g.V().count()
```

Note that `withComputer()` has lots of useful overloads.

```
g = graph.traversal().withComputer(h -> h.compute(SparkGraphComputer.class).workers(10))
```

This change is "lightly breaking." For users, nothing changes. The previous `Builder` model still exists in a `Deprecated` state. All graph system providers have to do is:

* Implement `XXXGraphProvider.getGraphComputer()` (if and only if they support `GraphComputer`).
* Change `traverser.getEngine().isGraphComputer()` to `traversal.getStrategies().onGraphComputer()` if they have custom `TraversalStrategy` implementations.
* Change `implements EngineDependent` to `implements GraphComputing` if they have custom steps that implemented `EngineDependent`.

CHANGELOG:

```
* Refactored `TraversalSource` model to allow fluent-method construction of `TraversalSources`.
* Deprecated the concept of a `TraversalSource.Builder`.
* Removed the concept of a `TraversalEngine`. All `Traversal` modulations now mediated by `TraversalStrategies`. (*breaking*)
* Added `SideEffectStrategy` for registering sideEffects in a spawned `Traversal`.
* Added `SackStrategy` for registering a sack for a spawned `Traversal`.
* Added `RequirementsStrategy` and `RequirementsStep` for adding dynamic `TraverserRequirements` to a `Traversal`.
* Removed `EngineDependentStrategy`.
* Renamed step interface `EngineDependent` to `GraphComputing` with method `onGraphComputer()`. (*breaking*)
* Cleaned up various `TraversalStrategy` tests now that `TraversalEngine` no longer exists.
```

### CODE REVIEW

**Comment by okram** [comment]
VOTE +1. `mvn clean install`, integration tested, and built/published docs.

You can review the docs here: http://tinkerpop.apache.org/docs/3.2.0-SNAPSHOT/reference/

**Comment by okram** [comment]
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3:16:47.194s
[INFO] Finished at: Tue Feb 09 14:06:43 MST 2016
[INFO] Final Memory: 96M/731M
[INFO] ------------------------------------------------------------------------
```

**Comment by okram** [comment]
Note that when TINKERPOP-1140 is completed, `traversal.getStrategies().onGraphComputer()` will be replaced by `TraversalHelper.onGraphComputer(traversal)`. Minor note as this is one of the breaking changes for providers.

**Comment by dkuppitz** [comment]
* `mvn clean install`: passed
* integration tests (incl. Neo4j): passed

VOTE: +1

One negative note though: Strategies are mainly respsonsible for a significant performance gap between graph methods and their respective traversal methods. As we've seen in the past, `.stream()...` performs terrible compared to an old school `for` loop, hence I don't think we should use `.stream()` so frequently in new code. Better we get rid of `.stream()` altogether.

**Comment by okram** [comment]
@dkuppitz -- where in particular are you seeing the use of `stream()`?

**Comment by dkuppitz** [comment]
New code:

* https://github.com/apache/incubator-tinkerpop/pull/215/files#diff-61ffd0f149055394746c1d94ccab52e3R65
* https://github.com/apache/incubator-tinkerpop/pull/215/files#diff-bd7750c1c674aeb94e058006af320abfR50
* https://github.com/apache/incubator-tinkerpop/pull/215/files#diff-61f8ab6e66876a272a1fa1f3556b3012R51
* https://github.com/apache/incubator-tinkerpop/pull/215/files#diff-3f79b4cdbc46d5f73ad1864f7d4402a5R80
* https://github.com/apache/incubator-tinkerpop/pull/215/files#diff-34c81b4d45231b961aa8f748f3f4a339R72
* https://github.com/apache/incubator-tinkerpop/pull/215/files#diff-94d7c8c44b3975d2312b04c7f54e500cR47
* https://github.com/apache/incubator-tinkerpop/pull/215/files#diff-b6bca124a8cddd1cd9a8c0b004cd1634R53

Old code, but touched by the commit:

*  https://github.com/apache/incubator-tinkerpop/pull/215/files#diff-0f4959bc7926d8e5fbd6395e96f19502R76

At least some of these code lines were probably copied from somewhere else as part of the refactoring process. However, as said before, it would probably be better to get rid of `stream()` once we stumble across it in the code we're working on.

**Comment by okram** [comment]
A response to each item in your list.

* This will go away when TINKERPOP-1140 is complete. This is a "staging method" for now.
* This is not a critical performance line of code. This is during `TraversalSource` construction which is like saying "a database connection creation method uses stream."
* Same as previous.
* Same as previous -- submitting a `GraphComputer` job is crazy costly relative to this simple `stream()`.
* This will go away when TINKERPOP-1140 is complete. This is a "staging method" for now.
* This is test suite setup code. Performance doesn't matter.
* Same as previous.

To your "old code" reference:

* Yes, we should not use `stream()` here. This class needs to be blazing fast. I believe you and I are the author of this class and we should fix it. That is for another ticket.

NOTE: We should also remove all the `stream()` work in `StarGraph` (there is a butt load).

**Comment by spmallette** [comment]
Did a basic build with `mvn clean install` and reviewed docs - looks good:

VOTE +1

**Pull request merged**
