### PR TITLE
slf4j-log4j12 / log4j is only required for testing (TINKERPOP-1151) 

### PR DESCRIPTION
**Pull request by ceefour**
slf4j-log4j12 / log4j is only required for testing (TINKERPOP-1151)

### CODE REVIEW

**Comment by ceefour** [comment]
Okay @spmallette, I hope this is good :)

**Comment by spmallette** [comment]
did you try to build this? it doesn't build for me or travis/appveyor....

**Comment by pluradj** [comment]
build fails for me too, similar to travis

**Comment by spmallette** [comment]
@ceefour do you expect to make any revisions to this to get it to build?

**Comment by spmallette** [comment]
@ceefour anything new here with respect to getting this PR to build? if not, I'd like to close this.

**Comment by ceefour** [comment]
@spmallette Sorry, I'm currently fixing it now.

**Comment by ceefour** [comment]
@spmallette Fixed :)

**Comment by spmallette** [comment]
I'm not sure if this is right still.  The tests run but i still see this message in every module during build:

```text
Running org.apache.tinkerpop.gremlin.util.function.ScriptEngineLambdaTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.648 sec - in org.apache.tinkerpop.gremlin.util.function.ScriptEngineLambdaTest
Running org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutorTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

I haven't even gotten to testing the actual console distribution, server distributions, hadoop/spark/giraph logging.  Can you please post some evidence of these things working in full? without that, i don't think i can VOTE positively on this.

**Comment by ceefour** [comment]
@spmallette I've made sure every module has `slf4j-log4j12` as before, but either `runtime` or `test` scoped depending on whether it's an app or library.

image

**Comment by spmallette** [comment]
Something is still wrong:

```text
$ bin/gremlin.sh

         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
plugin activated: tinkerpop.server
plugin activated: tinkerpop.utilities
plugin activated: tinkerpop.tinkergraph
gremlin> cluster = Cluster.open()
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
==>localhost/127.0.0.1:8182
gremlin> 
```

I'll ask again that you test this more carefully and exhaustively.  Our binary distributions can't have slf4j errors in it.  Where are your tests of gremlin server, spark, giraph, and hadoop? do they log as needed?

**Comment by ceefour** [comment]
I see, it's logging fine from the built artifacts but not for the assembly... need to fix `src/main/assembly/*.xml` as well

**Comment by spmallette** [comment]
@ceefour it seems strange that you should have to touch the assembly files to get this to work properly. without putting much thought into it on my part, that doesn't seem like the right way to go.  do you intend to return to this PR or should we just close this at this point?

**Comment by ceefour** [comment]
@spmallette Sorry i forgot to actually make the change.

The assembly files were incorrect from the start since it only includes "compile" dependencies meaning "runtime" dependencies (which didn't exist before) were left out. I made the slf4j impl/log4j runtime or test dependencies since they're not required to compile (and users of the library can use any slf4j impl, not just log4j, i.e. me and Spring Boot )

**Comment by spmallette** [comment]
It's been a few weeks, so I thought I would check-in - do you still plan to try to correct this PR?

**Comment by spmallette** [comment]
I'm closing this for now as there hasn't been any movement on it in about a month. Please feel free to re-open when there is something that fully works.

**Pull request closed without merging**
