### PR TITLE
TINKERPOP3-952 Adding example of a property with list cardinality.

### PR DESCRIPTION
**Pull request by twilmes**
https://issues.apache.org/jira/browse/TINKERPOP3-952 

I added an example of adding a property with a list cardinality along with an explanation.  @rjbriody if you get a chance, let me know if this is along the lines of what you were thinking.  I checked things out by doing a dry run of the docs generation.

### CODE REVIEW

**Comment by twilmes** [comment]
Updated per @rjbriody suggestion to qualify Cardinality.list.

VOTE +1

I went RTC for this since it was my first doc update but if you guys think this is overkill, I'll do CTR on minor doc updates going forward.

**Comment by PommeVerte** [comment]
This looks simple enough. Lets wait to hear back from @rjbriody but it gets my VOTE: +1

**Comment by spmallette** [comment]
bob gave a thumbs up on the JIRA ticket so +1 from me.  you're good to merge @twilmes 

btw, your doc changes to the code look sufficiently simple to get by with a `--dryRun` for testing, but if you haven't done so already you should probably try to figure out how to do a full run.  another neat way to test is to copy/paste the code to the console to be sure it works nicely there.

**Comment by twilmes** [comment]
Sounds good @spmallette.  I did the old copy/paste into the shell but I need to get the full run going.  Tried it quickly once and got a hadoop error so I'll go back and check the docs out and figure out my mistake.

**Comment by okram** [comment]
This has 3 +1 VOTES. @twilmes -- do you plan to merge this into master/?

**Pull request merged**
