### PR TITLE
TINKERPOP-1225: Do a "rolling reduce" for GroupXXXStep in OLAP.

### PR DESCRIPTION
**Pull request by okram**
https://issues.apache.org/jira/browse/TINKERPOP-1225

We now can do mid-barrier reductions in with `group()` on OLAP. This is huge as this means that if you have an reducer in your `by()`-valueTraversal, the stream is constantly reduced to limit memory consumption. Its more expensive in terms of time (not by much) for small data, but for large data, no worries about OME with group() (both both OLTP and OLAP).

CHANGELOG

```
* `GroupStep` and `GroupSideEffectStep` make use of mid-traversal reducers to limit memory consumption in OLAP.
``` 

VOTE +1

### CODE REVIEW

**Comment by okram** [comment]
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Apache TinkerPop .................................. SUCCESS [4.350s]
[INFO] Apache TinkerPop :: Gremlin Shaded ................ SUCCESS [2.302s]
[INFO] Apache TinkerPop :: Gremlin Core .................. SUCCESS [40.323s]
[INFO] Apache TinkerPop :: Gremlin Test .................. SUCCESS [12.404s]
[INFO] Apache TinkerPop :: Gremlin Groovy ................ SUCCESS [42.373s]
[INFO] Apache TinkerPop :: Gremlin Groovy Test ........... SUCCESS [6.747s]
[INFO] Apache TinkerPop :: TinkerGraph Gremlin ........... SUCCESS [3:24.962s]
[INFO] Apache TinkerPop :: Gremlin Benchmark ............. SUCCESS [10.390s]
[INFO] Apache TinkerPop :: Hadoop Gremlin ................ SUCCESS [11:27.951s]
[INFO] Apache TinkerPop :: Spark Gremlin ................. SUCCESS [7:01.345s]
[INFO] Apache TinkerPop :: Giraph Gremlin ................ SUCCESS [2:41:47.692s]
[INFO] Apache TinkerPop :: Neo4j Gremlin ................. SUCCESS [17:53.279s]
[INFO] Apache TinkerPop :: Gremlin Driver ................ SUCCESS [10.358s]
[INFO] Apache TinkerPop :: Gremlin Server ................ SUCCESS [12:52.175s]
[INFO] Apache TinkerPop :: Gremlin Console ............... SUCCESS [1:25.610s]
[INFO] Apache TinkerPop :: Gremlin Archetype ............. SUCCESS [0.086s]
[INFO] Apache TinkerPop :: Archetype - TinkerGraph ....... SUCCESS [4.702s]
[INFO] Apache TinkerPop :: Archetype - Server ............ SUCCESS [10.319s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3:38:17.858s
[INFO] Finished at: Wed Mar 30 22:57:45 MDT 2016
[INFO] Final Memory: 99M/765M
[INFO] ------------------------------------------------------------------------
```

**Comment by spmallette** [comment]
VOTE +1

**Comment by twilmes** [comment]
VOTE: +1

**Comment by dkuppitz** [comment]
VOTE: +1

**Pull request merged**
