### PR TITLE
TINKERPOP-1023: Add a spark variable in SparkGremlinPlugin like we do hdfs for HadoopGremlinPlugin

### PR DESCRIPTION
**Pull request by okram**
https://issues.apache.org/jira/browse/TINKERPOP-1023

Like `hdfs` there is now `spark` which allows the user to manage their persisted contexts. In essence, the Spark Server looks like a file system with (named) RDDs accessible. For instance, you can `spark.ls()`, `spark.rm()`, `spark.describe()`. I added a `SparkGremlinPluginTest` which ensures that all the proper imports/etc. work in the Console. I also added the information the reference docs. I published the reference docs so people can see it in action:

http://tinkerpop.apache.org/docs/3.1.1-SNAPSHOT/reference/#sparkgraphcomputer  (scroll down to "Using A Persisted Context" section)

VOTE +1. (`mvn clean install` and Spark integration tests)

### CODE REVIEW

**Comment by okram** [comment]
Note that I also tested this with Spark Server and it works great. This is a really really cool thing.

**Comment by dkuppitz** [comment]
* `mvn clean install`: worked
* manual tests using the new `spark` object: failed

```
daniel@cube /projects/apache/test/incubator-tinkerpop/gremlin-console/target/apache-gremlin-console-3.1.1-SNAPSHOT-standalone (TINKERPOP-1023) $ HADOOP_GREMLIN_LIBS=`pwd`/ext/hadoop-gremlin/lib:`pwd`/ext/spark-gremlin/lib bin/gremlin.sh

         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
plugin activated: tinkerpop.server
plugin activated: tinkerpop.utilities
WARN  org.apache.hadoop.util.NativeCodeLoader  - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
INFO  org.apache.tinkerpop.gremlin.hadoop.structure.HadoopGraph  - HADOOP_GREMLIN_LIBS is set to: /projects/apache/test/incubator-tinkerpop/gremlin-console/target/apache-gremlin-console-3.1.1-SNAPSHOT-standalone/ext/hadoop-gremlin/lib:/projects/apache/test/incubator-tinkerpop/gremlin-console/target/apache-gremlin-console-3.1.1-SNAPSHOT-standalone/ext/spark-gremlin/lib
plugin activated: tinkerpop.hadoop
plugin activated: tinkerpop.spark
plugin activated: tinkerpop.tinkergraph
gremlin> spark
No such property: spark for class: groovysh_evaluate
Display stack trace? [yN] N
gremlin> spark.create("local[4]")
No such property: spark for class: groovysh_evaluate
Display stack trace? [yN] N
gremlin> 
```

What am I missing here?

**Comment by okram** [comment]
@dkuppitz -- did you clear your grapes?

**Comment by dkuppitz** [comment]
Yes, that was the issue.

**Update**:

* `mvn clean install`: worked
* manual tests using the new `spark` object: worked

VOTE: +1

**Comment by spmallette** [comment]
Builds and tests nicely.  Did some simple manual tests with `spark` object - worked.

Just a reminder that upgrade docs are lagging a bit behind all the spark work that's been done.  

VOTE: +1

**Pull request merged**
