### PR TITLE
Update hadoop to 2.7.2

### PR DESCRIPTION
**Pull request by ceefour**

### CODE REVIEW

**Comment by ceefour** [comment]
It's weird that hadoop-client and hadoop-hdfs do not agree on netty version. This should be fixable.

**Comment by ceefour** [comment]
Root issue reported to Hadoop project: https://github.com/apache/hadoop/pull/84

**Comment by steveloughran** [comment]
Why the two versions? hdfs netty went in later, MR netty hasn't (yet) updated, then there's the fear of breaking things downstream. Hadoop 2.8 splits hdfs client libs out into their own JAR; there's no dependency in netty 4 in hadoop-hdfs-client at all.

**Comment by spmallette** [comment]
@okram i think you have to lead the review on this hadoop stuff.

**Comment by okram** [comment]
VOTE +1. 

I merged locally (had to tweak a few other things -- docs and Manifest stuff, but works). This appears okay for `tp31` and an upmerge to `master`.

**Comment by spmallette** [comment]
VOTE +1

**Comment by dkuppitz** [comment]
VOTE: +1

**Comment by okram** [comment]
Note that I also verified that this still works with Hadoop 2.7.1 by building the docs with Hadoop 2.7.1 running.

**Comment by okram** [comment]
Note that I also just merged master/ and all is good in the (proverbial) hood.

**Pull request merged**
