### PR TITLE
Added another `edge()` method in `ScriptElementFactory`

### PR DESCRIPTION
**Pull request by dkuppitz**
Added another `edge()` method in `ScriptElementFactory` that allows to set explicit edge ids.

### CODE REVIEW

**Comment by okram** [comment]
Why do you use a different order to your methods? Why not copy the parameterization from `Vertex`?

```
id, ?vertex?, label, vertex, properties...
```

**Comment by okram** [comment]
I studied `ScriptElementFactory` and am thinking that API is poorly designed. Here are my concerns:

```
protected class ScriptElementFactory {

        private final StarGraph graph;

        public ScriptElementFactory() {
            this.graph = StarGraph.open();
        }

        public Vertex vertex(final Object id) {
            return vertex(id, Vertex.DEFAULT_LABEL);
        }

        public Vertex vertex(final Object id, final String label) {
            final Iterator<Vertex> vertices = graph.vertices(id);
            return vertices.hasNext() ? vertices.next() : graph.addVertex(T.id, id, T.label, label);
        }

        public Edge edge(final Vertex out, final Vertex in) {
            return edge(out, in, Edge.DEFAULT_LABEL);
        }

        public Edge edge(final Vertex out, final Vertex in, final String label) {
            return out.addEdge(label, in);
        }
    }
```

`ScriptElementFactory` should be a `GraphWrapper` so that the APIs are consistent.

```
ScriptGraph.addVertex()
ScriptVertex.addEdge()
```

Its weird that you diverge from the standard pattern for seemingly no reason except the `vertex(id,label)`-method logic.

**Comment by okram** [comment]
I don't even know why you have `ScriptElementFactory` now. Why not just make available a static `getOrCreate()` and get rid of `ScriptElementFactory` ?

**Comment by dkuppitz** [comment]
I can think about another API for TP 3.2, but this PR is for TP 3.1.2.

**Comment by okram** [comment]
I was looking more into this. I think we should `Deprecate` ScriptElementFactory. Why not just use `StarGraph` directly? Your `vertex()`-logic is identical to `StarGraph.addVertex()`. Note that if its the `StarVertex`, it comes right back. If its not a new `StarAdjacentVertex` is created and returned.

I would recommend.

1. Do not add more methods to `ScriptElementFactory`.
2. Deprecate `ScriptElementFactory` in TP 3.2.0.
3. Update to use `StarGraph` directly, but if the user's script has a method for `ScriptElementFactory`, then use that method.

**Comment by dkuppitz** [comment]
https://issues.apache.org/jira/browse/TINKERPOP-1144

**Comment by dkuppitz** [comment]
What's the remaining lifetime of something that is marked as deprecated? Can we deprecate ScriptElementFactory for 3.1.2 and remove it in 3.2.0?

**Comment by okram** [comment]
No. We leave it around indefinitely. We may do a "big purge" at 3.5.0.

**Comment by dkuppitz** [comment]
I've found no way to inject the `graph` as a global variable. I can either add another `parse` method parameter, which would break existing code, or I can add `ScriptElementFactory::getGraph()`.

**Pull request closed without merging**
