### PR TITLE
TINKERPOP-1027: Merge view prior to writing graphRDD to output format/rdd

### PR DESCRIPTION
**Pull request by okram**
https://issues.apache.org/jira/browse/TINKERPOP-1027

We had a bug in Spark `graphRDD` writing that showed itself on for particular providers. @dalaro provided realized the problem and provided a solution. This PR implements @dalaro's recommended fix. This fix also removes the need for `reduceByKey()` (though backwards compatible if you do still have it) and allowed us to always use `GryoSerialization` with Spark. This is rad. I added a few more required serialization registers to `GryoSerialization` and all the test cases pass. I also added some more test cases to ensure proper functioning.

* Spark integration tests passed.
* `mvn clean install` passed.

VOTE +1.

### CODE REVIEW

**Comment by okram** [comment]
NOTE: I originally had this work in TINKERPOP-1025, but that ticket is a completely different beast so I merged the work into a new ticket. TINKERPOP-1025 is still being dealt with.

**Comment by dalaro** [comment]
[My comment on TINKERPOP-1025](https://issues.apache.org/jira/browse/TINKERPOP-1025?focusedCommentId=15045307&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15045307) now applies to this PR.   The change involving {{prepareFinalGraphRDD}} is what matters to me, and when I tested a TINKERPOP-1025 HEAD that includes both of these commits, it solved my problem.  So, +1 (non-voting) from me.

**Comment by okram** [comment]
I made it so that SparkGremlin works like Spark JobServer (https://github.com/spark-jobserver/spark-jobserver/). It ensures that RDDs are not garbage collected by maintaining a static `Spark` class that holds a `ConcurrentHashMap` of RDDs. Thus, Spark is like a "file system" in that RDDs can be `ls()`, `rm()`, etc. This was necessary to get "slow" `mvn clean install` to build correctly where RDDs are NOT GC'd by Spark context cleaner.

**Comment by twilmes** [comment]
Awesome, looks good and tests pass for me.

VOTE +1

**Comment by spmallette** [comment]
tests run locally for me:

VOTE +1

btw, your intellij settings might need to get fixed up - they are doing wildcards for static imports:

https://github.com/apache/incubator-tinkerpop/pull/172/files#diff-889af44a6f21b3700e537cc41765435aR40

**Pull request merged**
