### PR TITLE
TINKERPOP-1020 Provide --dryRun selectivity for "half publishing" docs.

### PR DESCRIPTION
**Pull request by dkuppitz**
**Process all docs**:

```sh
bin/process-docs.sh
```

**Dry-run all docs**:

```sh
bin/process-docs.sh -d
bin/process-docs.sh --dryRun
```

**Process only `the-graph.asciidoc` and `the-traversal.asciidoc`** (dry-run the others):

```sh
bin/process-docs.sh -f the-graph,the-traversal
bin/process-docs.sh --fullRun the-graph,the-traversal
```

**Dry-run `the-graph.asciidoc` and `the-traversal.asciidoc`** (process the others):

```sh
bin/process-docs.sh -d the-graph,the-traversal
bin/process-docs.sh --dryRun the-graph,the-traversal
```

VOTE: +1

### CODE REVIEW

**Comment by spmallette** [comment]
@dkuppitz github is showing that there are conflicts to resolve on this branch - can you rebase on tp31 please?

**Comment by dkuppitz** [comment]
Done.

**Comment by spmallette** [comment]
Did some tests on this  - looks like it works as advertised. @dkuppitz you probably want to rebase on tp31 again and fix up the CHANGELOG before you merge as this will go to 3.1.3 now and not 3.1.2.

VOTE +1

**Comment by spmallette** [comment]
@dkuppitz quick question - does the "half-processing" work for tutorials or other docs? or just the reference docs? for instance, how would i just generate docs for the getting started tutorial?

**Comment by dkuppitz** [comment]
> how would i just generate docs for the getting started tutorial?

```sh
bin/process-docs.sh -f index
```

Obviously it will now process every `index.asciidoc` file and `dryRun` all others. I could make it so that you have to specify the full path to the asciidoc file to full/dryRun.

**Comment by spmallette** [comment]
not supremely urgent, but i think the full path would be better, imo.

**Comment by dkuppitz** [comment]
I'll make that change for this PR as it seems to take forever to get a 3rd +1 anyways.

**Comment by okram** [comment]
Very cool PR. Thanks @dkuppitz -- VOTE +1.

**Comment by dkuppitz** [comment]
Things to add/change:

* only accept either a path to one or more files or
* a directory which then acts as a wildcard for `directory/*.asciidoc`

**Pull request merged**
