### PR TITLE
Addition of javadoc displaying in gremlin console

### PR DESCRIPTION
**Pull request by xristosoik**
I create a package which implement all the necessary functionalities for parsing and displaying of javadocs in the gremlin console. Also I add 3 commands in the console which are responsible for the connection between console and package. Last but not least I create some test to verify the reliability.

The use of this commands is

// This is a command for loading of the documentation of a Class*.
gremlin> :importdocs "Graph"
//This is a command for displaying the documentation of a method**.
gremlin> :docs "addVertex"
//This id a command which returns the current loaded Class.
gremlin> :currdocs

*Every time is only one Class's loaded documentation.
** If there are overloaded classes displays all of them the one after the other.  
screenshot from 2015-06-07 19 12 17

### CODE REVIEW

**Comment by mhfrantz** [comment]
After you've addressed the feedback, you might want to clean up this branch by rebasing to master in order to remove the various merge commits.

**Comment by mhfrantz** [comment]
Indentation looks a bit uneven. If you use IntelliJ or another code editor, it can probably clean that up for you automatically.

**Comment by xristosoik** [comment]
This will work but with the web parsing. There are 2 strategies the one is trying to find it local and the other is on web. The second is used only if the first fails. Although I will try your solution also.

**Comment by okram** [comment]
Where are we with this? Any movement? Ready to merge?

**Comment by xristosoik** [comment]
I am sorry for the delayed answer! I have a lot of time pressure for my
work, so I haven't finished it. I am willing to but I need some time.
Sorry for any inconvenience
Regards,
Christos
> Where are we with this? Any movement? Ready to merge?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/apache/incubator-tinkerpop/pull/71#issuecomment-126943079


×ñÞóôïò Ïéêïíüìïõ
ôçë. 6947359872
åíáëëáêôéêÞ äéåýèõíóç çëåêôñïíéêü ôá÷õäñïìåßï
chrikon1994@gmail.com

**Comment by spmallette** [comment]
@xristosoik I was wondering if you intend to come back to this pull request.  it was the start of a nice body of work.  any thoughts on how this could move forward?

**Comment by xristosoik** [comment]
I am intend to improve it by convert some part in groovy and add testing in as many part as it is possible(I have not forgot your feedback). However things had happened after this pull request and I did not have find any time to do all those I had planned to. Of course do not hesitate to tell me if you have any new ideas.

**Comment by spmallette** [comment]
We've had some discussion on the mailing list about this pull request:

https://lists.apache.org/thread.html/Zs1050tpg3vfz5n

and it seems the consensus is that we should probably close it at this point. Aside from it being nearly a year old without any additional activity, we think that this feature, if it were to exist, should be a feature of groovysh and not something tied to TinkerPop. 

Unless you have concerns, I will close this pull request from my end.

**Pull request closed without merging**
