### PR TITLE
improve predicate doc

### PR DESCRIPTION
**Pull request by pluradj**
https://groups.google.com/d/msg/gremlin-users/V9wHagF2SvY/FBwe1zkbAwAJ

### CODE REVIEW

**Comment by okram** [comment]
VOTE +1. This is so minor, you could just CTR it.

**Comment by pluradj** [comment]
LOL, you're right

**Comment by pluradj** [comment]
are we putting doc updates into tp31 also?

**Comment by okram** [comment]
Please.

**Comment by dkuppitz** [comment]
Now that the PR exists, you'll need the vote, hence...

VOTE: +1

**Comment by pluradj** [comment]
Vote: +1 thanks

**Pull request merged**
