### PR TITLE
TINKERPOP3-990 Removed mixed typing in VertexPropertyTest

### PR DESCRIPTION
**Pull request by n-tran**
Converted integer value to string to maintain type

https://issues.apache.org/jira/browse/TINKERPOP3-990

### CODE REVIEW

**Comment by spmallette** [comment]
Thanks for this.  Note that since you submitted this PR, there are two other tests that have been identified to have this problem (see JIRA). Can you please amend your PR to include those fixes?

**Comment by n-tran** [comment]
Fixed the two tests, ready for review

**Comment by PommeVerte** [comment]
This is straightforward enough. Don't know if this needs to go through RTC but just incase:

VOTE: +1

**Comment by okram** [comment]
VOTE +1.

This is consistent with `weight` being used as `Double` in `MODERN`.

```
gremlin> g.E().values('weight').limit(1).map{it.get().getClass()}
==>class java.lang.Double
```

**Comment by spmallette** [comment]
VOTE +1 - about to merge

**Pull request merged**
