### PR TITLE
TINKERPOP-1310: Allow OLAP to return properties as Detached

### PR DESCRIPTION
**Pull request by okram**
https://issues.apache.org/jira/browse/TINKERPOP-1310

I created {{HaltedTraverserFactoryStrategy}} which is an OLAP strategy that can return {{DetachedXXX}} elements to the user instead of always just the plain (data-less) {{ReferenceXXX}}. Also did lots of nick nack optimizations and documentation to {{TraversalVertexProgram}}.

CHANGELOG
```
* Added `HaltedTraverserFactoryStrategy` to allow users to get back different element detachments in OLAP.
```

VOTE +1. (Giraph still running)

### CODE REVIEW

**Comment by okram** [comment]
Sorry. Giraph is breaking on integration tests. Easy fix. Will post BUILD status when full integration tests complete.

**Comment by okram** [comment]
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Apache TinkerPop .................................. SUCCESS [4.017s]
[INFO] Apache TinkerPop :: Gremlin Shaded ................ SUCCESS [2.300s]
[INFO] Apache TinkerPop :: Gremlin Core .................. SUCCESS [39.517s]
[INFO] Apache TinkerPop :: Gremlin Test .................. SUCCESS [14.326s]
[INFO] Apache TinkerPop :: Gremlin Groovy ................ SUCCESS [39.994s]
[INFO] Apache TinkerPop :: Gremlin Groovy Test ........... SUCCESS [9.066s]
[INFO] Apache TinkerPop :: TinkerGraph Gremlin ........... SUCCESS [3:24.378s]
[INFO] Apache TinkerPop :: Gremlin Benchmark ............. SUCCESS [4.740s]
[INFO] Apache TinkerPop :: Hadoop Gremlin ................ SUCCESS [5:45.304s]
[INFO] Apache TinkerPop :: Spark Gremlin ................. SUCCESS [8:55.587s]
[INFO] Apache TinkerPop :: Giraph Gremlin ................ SUCCESS [2:54:44.107s]
[INFO] Apache TinkerPop :: Neo4j Gremlin ................. SUCCESS [1:09:03.609s]
[INFO] Apache TinkerPop :: Gremlin Driver ................ SUCCESS [10.417s]
[INFO] Apache TinkerPop :: Gremlin Server ................ SUCCESS [13:16.404s]
[INFO] Apache TinkerPop :: Gremlin Console ............... SUCCESS [1:24.872s]
[INFO] Apache TinkerPop :: Gremlin Archetype ............. SUCCESS [0.091s]
[INFO] Apache TinkerPop :: Archetype - TinkerGraph ....... SUCCESS [4.704s]
[INFO] Apache TinkerPop :: Archetype - Server ............ SUCCESS [10.492s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4:38:54.425s
[INFO] Finished at: Wed May 25 20:36:18 MDT 2016
[INFO] Final Memory: 99M/712M
[INFO] ------------------------------------------------------------------------
```

**Comment by spmallette** [comment]
Tests hung for some reason during gremlin server integration testing with `docker/build.sh -t -n -i`, but i then re-ran just those tests and everything worked fine. Not sure what happened there but the net effect is that all the tests passed.

VOTE +1

**Comment by dkuppitz** [comment]
> Also did ... documentation to `TraversalVertexProgram`.

I don't see any additions to the docs in this PR (neither user docs nor JavaDocs). Just pointing that out in case you forgot to commit / push something. Either way ...

VOTE: +1

**Comment by okram** [comment]
I'm sort of disinterested in adding this to the user docs right now given that its a bit "in the air" how this will tie in with Gremlin Server. I think once @spmallette does the Gremlin Server work with `HaltedTraverserStrategy`, he will add it to GremlinServer docs (`RemoteGraph`-style with a `NOTE` saying that the strategy is generally useful).

**Pull request merged**
