### PR TITLE
TINKERPOP-1125 Use the existing Host iterator

### PR DESCRIPTION
**Pull request by kieransherlock**
TINKERPOP-1125
Rather than creating a new iterator so skipping over a host in the pool.

### CODE REVIEW

**Comment by spmallette** [comment]
Glad you figured out how to get that pull request done - cool! A few things:

1. Travis is failing, but i dont think that's your fault - from the looks of the output it seems that Travis just died mid build somehow. I can test the build of your PR manually when the time comes.
1. could you quickly edit the name of your PR to be prefixed with the JIRA issue? That will allow our comments to hook into JIRA nicely for all comments on this ticket. In other words, just change the title to "TINKERPOP-1125 Use the existing Host iterator"
1. Did you run the Gremlin Server integration tests?  Basically, after `mvn clean install` you can just do: `mvn verify -DskipIntegrationTests=false -pl gremlin-server`. Those don't get executed by Travis. 

Sorry for the extra "administrative" work and I can't imagine you've broken anything with this change, but I just would like you to know what our pull request procedure looks like.  You can read more about such things here in the contributor docs:

http://tinkerpop.apache.org/docs/3.1.0-incubating/developer.html#_pull_request_format

Last but not least, the tp31 branch is currently frozen for release of 3.1.1-incubating which will go up for vote on Monday, so we probably won't look to merge this in until that is all settled.  Thanks again - please keep the PRs coming. :smile:

**Comment by kieransherlock** [comment]
1) I hope not!
2) Done.
3) No I didn't run these.  I'll do this shortly and update here.

**Comment by kieransherlock** [comment]
Ran the integration tests, no errors, though lots of stack traces.

Tests run: 135, Failures: 0, Errors: 0, Skipped: 10

[INFO]
[INFO] --- maven-failsafe-plugin:2.17:integration-test (performance-test) @ gremlin-server ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- maven-failsafe-plugin:2.17:verify (verify-integration-test) @ gremlin-server ---
[INFO] Failsafe report directory: incubator-tinkerpop/gremlin-server/target/failsafe-reports
[INFO]
[INFO] --- maven-failsafe-plugin:2.17:verify (verify-performance-test) @ gremlin-server ---
[INFO] Tests are skipped.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10:08 min
[INFO] Finished at: 2016-02-05T08:02:53-08:00
[INFO] Final Memory: 31M/466M
[INFO] ------------------------------------------------------------------------`

**Comment by spmallette** [comment]
thanks - travis is still failing strangely - same error.  not sure what's wrong there, but i still don't think it has anything to do with your PR.

**Comment by kieransherlock** [comment]
Hmm, I added a commit for TINKERPOP-1127 to my branch.  I guess it gets included in this PR, hope this is ok.

**Comment by spmallette** [comment]
Not a big deal if you find it necessary to combine the work, but better to create a new branch for each JIRA issue when possible. I notice that you are submitting your PR from your the `tp31` branch of your fork.  In the future you might prefer to create a branch from `tp31` called `TINKERPOP-1127` then submit your PR from that to our `tp31`.  In that way your work gets isolated a little better and you can pull in the latest from our `tp31` without conflict if you need to.  Just provides a bit more flexibility.

**Comment by kieransherlock** [comment]
FYI, works on my machine :-)


```
$ mvn clean install -Dci
...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Apache TinkerPop ................................... SUCCESS [  4.783 s]
[INFO] Apache TinkerPop :: Gremlin Shaded ................. SUCCESS [  2.002 s]
[INFO] Apache TinkerPop :: Gremlin Core ................... SUCCESS [ 25.039 s]
[INFO] Apache TinkerPop :: Gremlin Test ................... SUCCESS [  7.232 s]
[INFO] Apache TinkerPop :: Gremlin Groovy ................. SUCCESS [ 31.828 s]
[INFO] Apache TinkerPop :: Gremlin Groovy Test ............ SUCCESS [  4.698 s]
[INFO] Apache TinkerPop :: TinkerGraph Gremlin ............ SUCCESS [01:32 min]
[INFO] Apache TinkerPop :: Hadoop Gremlin ................. SUCCESS [04:58 min]
[INFO] Apache TinkerPop :: Spark Gremlin .................. SUCCESS [ 58.823 s]
[INFO] Apache TinkerPop :: Giraph Gremlin ................. SUCCESS [  5.119 s]
[INFO] Apache TinkerPop :: Neo4j Gremlin .................. SUCCESS [  0.983 s]
[INFO] Apache TinkerPop :: Gremlin Driver ................. SUCCESS [  5.888 s]
[INFO] Apache TinkerPop :: Gremlin Server ................. SUCCESS [  5.264 s]
[INFO] Apache TinkerPop :: Gremlin Console ................ SUCCESS [ 15.481 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 09:18 min
[INFO] Finished at: 2016-02-05T10:23:38-08:00
[INFO] Final Memory: 134M/1520M
[INFO] ------------------------------------------------------------------------
```

**Comment by spmallette** [comment]
yeah - don't know what's wrong with poor ol' travis

**Comment by spmallette** [comment]
I did some review of this.  it would be nice if you could add a test to cover TINKERPOP-1127.  Should be easy enough to do:

First, edit AbstractGremlinServerIntegrationTest to include a `startServer()` method:

```java
public void startServer() throws Exception {
    server.start().join();
}
````

Next, modify the existing test in `GremlinServerIntegrateTest.shouldFailOnDeadHost()` to call that method to restart the server toward the end of the test and include an assert to validate that a request can be made.  

Does that make sense?

**Comment by spmallette** [comment]
I've merged this PR to a TinkerPop branch called `TINKERPOP-1125-to-1127` for internal code review.   it covers this PR and #213  

That branch looks all good with:

```text
mvn clean install && mvn verify -pl gremlin-server -DskipIntegrationTests=false
```

I will update CHANGELOG after merge.  

VOTE +1

**Comment by okram** [comment]
VOTE +1.

**Comment by dkuppitz** [comment]
Looks good.

VOTE: +1

**Pull request merged**
