### PR TITLE
TINKERPOP-1234: program() step that takes arbitrary vertex programs

### PR DESCRIPTION
**Pull request by okram**
https://issues.apache.org/jira/browse/TINKERPOP-1234

We now have `GraphTraversal.program(VertexProgram)`. This allows users to do things such as:

```
g.V().out("bought").in("bought").program(CollaborativeFilteringVertexProgram.build()....)
```

Behaves just like any other `VertexProgramStep` where:

```
g.V().pageRank() == g.V().program(PageRankVertexProgram...)
```

CHANGELOG

```
* Added `GraphTraversal.program(VertexProgram)` to allow arbitrary user vertex programs in OLAP.
```

VOTE +1. @dkuppitz tested it with his use case as well.

### CODE REVIEW

**Comment by dkuppitz** [comment]
VOTE: +1

**Comment by spmallette** [comment]
I took a failure on:

```text
ProgramTest$Traversals>ProgramTest.g_V_programXpageRankX:57 null
```

when doing just `mvn clean install`...problem?  Travis has the same problem. Failing against Gremlin Server so it must be `RemoteGraph` related.

**Comment by okram** [comment]
Huh. I don't know why I didn't catch that. We already OPT_OUT of a related in `RemoteGraph`.

```
@Graph.OptOut(
        test = "org.apache.tinkerpop.gremlin.process.computer.ranking.pagerank.PageRankVertexProgramTest",
        method = "*",
        reason = "RemoteGraph does not support direct Graph.compute() access")
```

Just OPT'd_OUT of the one above. Running `mvn clean install` right now.

**Comment by spmallette** [comment]
VOTE +1

**Pull request merged**
