### PR TITLE
TINKERPOP3-909: Improve steps that handle numeric data

### PR DESCRIPTION
**Pull request by dkuppitz**
[TINKERPOP3-909: Improve steps that handle numeric data](https://issues.apache.org/jira/browse/TINKERPOP3-909)

Integrated `NumberHelper` in `SumStep`, `MinStep`, `MaxStep` and `MeanStep` (`local` and `global` step variants). Had to change a few test methods where we now get different (but more appropriate) result types.

All tests passed for me.

VOTE: +1

### CODE REVIEW

**Comment by okram** [comment]
I review the code. Solid. Can't believe you go `MeanGlobalStep` to work too. I also `mvn clean install`'d the branch and all passes.

SIDENOTE: Daniel, the quantum Gremlin stuff is proving some practical results where I think wave dynamics + your `NumberHelper` work, we will be able to do exclusive or, and, disjoint union, etc. without using memory structures! 3.2.0 is going to get nasty.

VOTE +1.

**Comment by okram** [comment]
Seems you always return a Double for `mean().`

```
gremlin> g.V().values('age').mean()
==>30.75
gremlin> __(2,2,4,4).mean()
==>3.0
```

Why is the MeanGlobalStep signature then <Number> ?

**Comment by spmallette** [comment]
I see the +1 from @okram above followed by a question and some more commits....is this still good for review or is there more work to do?

**Comment by okram** [comment]
This is good to go. I found a bug that @dkuppitz has since fixed and wrote a test case for.

**Comment by PommeVerte** [comment]
This looks good. Nice PR to have. `mvn clean install` passes for me. (minus the weird issues I'm having with spark atm)

VOTE: +1

**Pull request merged**
