### PR TITLE
TINKERPOP3-1011: HadoopGraph can't re-attach when the InputFormat is not a FileInputFormat

### PR DESCRIPTION
**Pull request by okram**
https://issues.apache.org/jira/browse/TINKERPOP3-1011

I really half-assed our `InputRDD` work in 3.1.0. Well, it works, but for some providers they have to do stupid work arounds. The reason I never caught the problem was that I didn't have a robust test infrastructure for it. I have since rectified the situation and more. The `SparkGraphComputer` integration tests now choose between using Gryo, GraphSON, or InputRDD as the source data. Thus, we are able to test `SparkGraphComptuer` without any communication to Hadoop HDFS.

I also solved a long time serialization issue with `WrappedArray` in `GryoSerializer`. This makes it so that we can now ALWAYS use `GryoSerializer`. I have changed all the respective tests to now use `GryoSerializer` and TADA happy happy Kryo.

Finally, `HadoopElementIterator` was always bound to use `FileInputFormat`. Why the hell did I leave it like that for so long?! Now ANY `InputFormat` can be streamed into Hadoop OLTP including `InputRDDs` via `InputRDDFormat`. Ballin'.

Finally finally, small tweak to `BulkLoaderVertexProgramTest` to use `target/test-output` as its data storage location (not `/tmp`).

Ran `mvn clean install` and did integration testing on `spark-gremlin/`. All is golden.

VOTE +1.

### CODE REVIEW

**Comment by okram** [comment]
Over the course of this evening, I ran full integration tests -- giraph, spark, and neo4j. they all passed.

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Apache TinkerPop .................................. SUCCESS [6.068s]
[INFO] Apache TinkerPop :: Gremlin Shaded ................ SUCCESS [2.772s]
[INFO] Apache TinkerPop :: Gremlin Core .................. SUCCESS [40.853s]
[INFO] Apache TinkerPop :: Gremlin Test .................. SUCCESS [12.714s]
[INFO] Apache TinkerPop :: Gremlin Groovy ................ SUCCESS [34.257s]
[INFO] Apache TinkerPop :: Gremlin Groovy Test ........... SUCCESS [7.461s]
[INFO] Apache TinkerPop :: TinkerGraph Gremlin ........... SUCCESS [4:16.902s]
[INFO] Apache TinkerPop :: Hadoop Gremlin ................ SUCCESS [6:53.244s]
[INFO] Apache TinkerPop :: Spark Gremlin ................. SUCCESS [6:02.920s]
[INFO] Apache TinkerPop :: Giraph Gremlin ................ SUCCESS [2:00:55.196s]
[INFO] Apache TinkerPop :: Neo4j Gremlin ................. SUCCESS [20:51.515s]
[INFO] Apache TinkerPop :: Gremlin Driver ................ SUCCESS [12.510s]
[INFO] Apache TinkerPop :: Gremlin Server ................ SUCCESS [10:28.470s]
[INFO] Apache TinkerPop :: Gremlin Console ............... SUCCESS [1:16.914s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2:52:42.398s
[INFO] Finished at: Wed Dec 02 21:12:39 MST 2015
[INFO] Final Memory: 100M/738M
[INFO] ------------------------------------------------------------------------
~/software/tinkerpop/tinkerpop3$
```

**Comment by okram** [comment]
@dkuppitz just realized why the Travis CI breaks.

Everytime you do `HadoopGraph` OLTP, you get:

```
[INFO] FileInputFormat - Total input paths to process : 1
```

And we do it alllllllot in all or tests. It doesn't show up in the GremlinConsole, only in our tests and I don't know how to turn it off. @dkuppitz said we can probably set the Logging in Travis to only be [WARN]. Dunno... I don't understand Java logging and with each passing year, I understand less.

**Comment by dkuppitz** [comment]
Ok, I think we can ignore the Travis errors for now. Worked like a charm on my local machine.

VOTE: +1

**Comment by spmallette** [comment]
VOTE: +1

**Comment by spmallette** [comment]
@okram don't worry about the branch conflicts to master - it's probably in the `.travis.yml` file.  you should keep the changes from your branch and replace them over the one in master when you merge.

**Comment by okram** [comment]
This was merged.

**Pull request closed without merging**
