### PR TITLE
TINKERPOP-732 .tree() serialization in GraphSON

### PR DESCRIPTION
**Pull request by PommeVerte**
I've had to upgrade jackson in `gremlin-shaded` to version `2.7.2` for this fix. I've made the appropriate changes to the `NOTICE` files.

This makes `tree()` work with the `GraphSON` serializers. I've added tests for `GraphSON` and `Gryo` + driver tests for `GraphSONMessageSerializer` and `GraphSONMessageGremlinSerializer`

What I've done for testing:
- `mvn clean install` **OK**
- `mvn verify -DskipIntegrationTests=false -pl gremlin-server` **OK**
- Ran tests with the php driver against `application/json`  **OK**

### CODE REVIEW

**Comment by okram** [comment]
Reviewed code as best I could given my knowledge of GraphSON serialization. VOTE +1.

**Comment by PommeVerte** [comment]
FYI we're waiting on @spmallette to get some info from the apache folk on the LICENSE/NOTICE structure for our shaded libs before we merge this.

**Comment by spmallette** [comment]
After I read the NOTICE more carefully I could see it was "non-standard" and likely didn't need to be added. I started a discussion on general@incubators for feedback.  There were mixed responses, but based on the feedback from Justin McLean, who usually reviews our releases, I think the approach should be to not add it at all:

http://mail-archives.apache.org/mod_mbox/incubator-general/201603.mbox/%3CFAA5F827-1A3D-4B01-8DC0-B0975CB264A3%40me.com%3E

Can you please amend the PR to revert those changes to NOTICE?

**Comment by PommeVerte** [comment]
done

**Comment by spmallette** [comment]
ran - `mvn clean install && mvn verify -pl gremlin-server -DskipIntegrationTests=false` and it succeeded. 

VOTE +1

**Comment by spmallette** [comment]
Please dont' forget to update the CHANGELOG when you merge since it isn't in the PR

**Comment by spmallette** [comment]
@PommeVerte noticed that neo4j tests are failing around this tree work:

```text
org.apache.tinkerpop.gremlin.neo4j.structure.MultiMetaNeo4jGraphStructureStandardTest
13:16:45 shouldSerializeTree(org.apache.tinkerpop.gremlin.structure.SerializationTest$GraphSONTest)  Time elapsed: 0.233 sec  <<< FAILURE!
13:16:45 java.lang.AssertionError: expected:<1> but was:<0>
13:16:45 	at org.junit.Assert.fail(Assert.java:88)
13:16:45 	at org.junit.Assert.failNotEquals(Assert.java:834)
13:16:45 	at org.junit.Assert.assertEquals(Assert.java:645)
13:16:45 	at org.junit.Assert.assertEquals(Assert.java:631)
13:16:45 	at org.apache.tinkerpop.gremlin.structure.SerializationTest$GraphSONTest.shouldSerializeTree(SerializationTest.java:385)
```

Can you please take a look?

**Comment by PommeVerte** [comment]
Going to look at this today.

**Comment by PommeVerte** [comment]
I had a quick look at this over breakfast this morning. I didn't account for Neo4J ids to be different from the basic modern ones. I'll CTR a fix for this as soon as I get off my train.

**Comment by spmallette** [comment]
Yeah - that makes sense - you have to do stuff like this:

https://github.com/apache/incubator-tinkerpop/blob/e92e45b8c0a6ea54d618a3a7aa3c41f83eddb79d/gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/SerializationTest.java#L70

**Comment by PommeVerte** [comment]
Ok I CTRed a fix for this. The following works for me now : 
- `mvn clean install -DincludeNeo4j`
- `mvn verify -DskipIntegrationTests=false -pl gremlin-server`

Let me know if all is good on your end as well.

**Pull request merged**
