### PR TITLE
slf4j-log4j12 / log4j is only required for testing (TINKERPOP-1151)

### PR DESCRIPTION
**Pull request by ceefour**
Issue: https://issues.apache.org/jira/browse/TINKERPOP-1151

### CODE REVIEW

**Comment by spmallette** [comment]
I guess we shouldn't have log4j be a standard dependency for `gremlin-core`, given use of slf4j, but I'm not sure making it a test dependency is right.  we package log4j by default in the `gremlin-console` and `gremlin-server`.  maybe those slf4j implementations should be added to those project directly and they are made a test dependency here?

**Comment by ceefour** [comment]
Yes, the "app" projects should have the runtime dependencies marked as "scope=runtime", and the "library" projects should have these dependencied marked as "scope=test"

**Comment by spmallette** [comment]
Cool - that makes sense - can you please amend your PR appropriately and take all the modules into account in doing so?

**Comment by spmallette** [comment]
Also, when you do that, can you please target this change at the `tp31` branch? I think we'd want to see this change for `3.1.2-incubating`.

**Comment by ceefour** [comment]
Replaced by #233

**Pull request closed without merging**
