### PR TITLE
TINKERPOP3-605 Cleanup of dependency management.

### PR DESCRIPTION
**Pull request by splatch**
Also moved existing name field to description since it's get really long. Module name is now prefixed with "Apache TinkerPop ::"

### CODE REVIEW

**Comment by okram** [comment]
Where are we with this? This seems very old -- if this work was already merged, please close this PR.

**Comment by spmallette** [comment]
This was never merged.  JIRA has the discussion on it.  Integration tests and performance tests failed to execute with this pull request.

**Comment by okram** [comment]
Given the age of this ticket, perhaps we should close it as I'm sure that its so divergent that writing it from scratch would be easier. @splatch

**Comment by splatch** [comment]
Due to dynamic nature of tinkerpop in incubation phase I was unable to provide up-to-date version of these changes. Some parts of these changes were already included in parent project thus it's valid to close this PR.

**Pull request closed without merging**
