### PR TITLE
TINKERPOP-1064 Allow a ClassResolver to be added to GryoMapper construction

### PR DESCRIPTION
**Pull request by spmallette**
https://issues.apache.org/jira/browse/TINKERPOP-1064

Not much to say here - This change just allows for some deep customization to the creation of the `GryoMapper`.  Tested with:

```text
mvn clean install && mvn verify -DskipIntegrationTests=false -DincludeNeo4j
```

### CODE REVIEW

**Comment by spmallette** [comment]
Going to amend this PR with changes from https://issues.apache.org/jira/browse/TINKERPOP-1066 - as these changes are all sort of related.

**Comment by spmallette** [comment]
VOTE +1 - note that this PR covers both: TINKERPOP-1064 and TINKERPOP-1066.

**Comment by okram** [comment]
`mvn clean install` passed. VOTE +1.

**Comment by dkuppitz** [comment]
Full integration test suite also passed.

VOTE: +1

**Pull request merged**
