### PR TITLE
TINKERPOP-1206 & TINKERPOP-1014: Bulk Traversers and Requirements Optimization

### PR DESCRIPTION
**Pull request by okram**
https://issues.apache.org/jira/browse/TINKERPOP-1206
https://issues.apache.org/jira/browse/TINKERPOP-1014

Two tangentially related issues are solved in this PR. The core of Gremlin is `Step`. We have this notion of an `ExpandableStepIterator` which knows either to get local traversers or traversers from the previous step. We use to have it where if you `addStarts(Iterator<Traverser>)`, it would add them to their own `MultiIterator`. This was pointless cause we don't get the benefit of bulking. Not only do we simplify the logic of this fundamental class, but we also reduce the amount of objects it creates/maintains and we all increase the likelihood of bulking (which is the ultimate potential optimization). The consequence is that we no longer support `O_Traverser` as bulking is ALWAYS required. This is fine -- very few traversals benefited from `O_Traverser` and all they gained was no `long` bulk field (trivial). `O_Traverser` is now abstract.

This got me into thinking about how we calculate requirements and I realized how insanely stupid we (me) were especially for `by()`-modulators where EVERY call to a local traversal (typically `by()`-traversals) were recalculating the requirements!!!! That is, a full walk through the traversal tree. I decided to make `TraverserGenerator` static to the root traversal and when it is needed (the first time), it calculates the requirements and locks in the generator. Likewise, for child traversals, they look to the root traversal for the generator and lock it in locally. Thus, all this notion of requirements being expensive just vanished. We should keep our "traverser species" as calculating requirements is now cheap.

CHANGELOG

```
* Optimized `ExpandableStepIterator` with simpler logic and increased the likelihood of bulking.
* Optimized `TraverserRequirement` calculations.
* `Step.processNextStart()` and `Step.next()` now return `Traverser.Admin<E>`. (*breaking*)
* `Traversal.addTraverserRequirement()` method removed. (*breaking*)
```

UPDATE

```
Step API Update
^^^^^^^^^^^^^^^^

The `Step` interface is fundamental to Gremlin. `Step.processNextStart()` and `Step.next()` both retuned `Traverser<E>`. We had so many `Traverser.asAdmin()` and direct typecast calls throughout (especially in `TraversalVertexProgram`) that it was deemed prudent to have `Step.processNextStart()` and `Step.next()` return `Traverser.Admin<E>`. Moreover it makes sense as this is internal logic where admins are always needed. Providers with their own step definitions will simply need to change their method signatures (no logic update is required -- save that `asAdmin()` can be safely removed if used). This is a trivial update to make.

Traversal API Update
^^^^^^^^^^^^^^^^^^^^

The way in which `TraverserRequirements` are calculated has been changed (for the better). The ramification is that post compilation requirement additions no longer make sense and should not be allowed. To enforce this, `Traversal.addTraverserRequirement()` method has been removed from the interface. Moreover, users should never be able to add requirements manually (this should all be inferred from the end compilation). However, if need be, there is always `RequirementStrategy` which will allow the user to add a requirement at strategy application time (though again, there should not be a reason to do so).
```

VOTE +1.

### CODE REVIEW

**Comment by okram** [comment]
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Apache TinkerPop .................................. SUCCESS [5.291s]
[INFO] Apache TinkerPop :: Gremlin Shaded ................ SUCCESS [2.445s]
[INFO] Apache TinkerPop :: Gremlin Core .................. SUCCESS [39.104s]
[INFO] Apache TinkerPop :: Gremlin Test .................. SUCCESS [12.225s]
[INFO] Apache TinkerPop :: Gremlin Groovy ................ SUCCESS [40.759s]
[INFO] Apache TinkerPop :: Gremlin Groovy Test ........... SUCCESS [6.183s]
[INFO] Apache TinkerPop :: TinkerGraph Gremlin ........... SUCCESS [3:22.053s]
[INFO] Apache TinkerPop :: Hadoop Gremlin ................ SUCCESS [5:29.659s]
[INFO] Apache TinkerPop :: Spark Gremlin ................. SUCCESS [7:09.631s]
[INFO] Apache TinkerPop :: Giraph Gremlin ................ SUCCESS [2:22:43.096s]
[INFO] Apache TinkerPop :: Neo4j Gremlin ................. SUCCESS [17:48.925s]
[INFO] Apache TinkerPop :: Gremlin Driver ................ SUCCESS [9.501s]
[INFO] Apache TinkerPop :: Gremlin Server ................ SUCCESS [11:55.276s]
[INFO] Apache TinkerPop :: Gremlin Console ............... SUCCESS [1:23.744s]
[INFO] Apache TinkerPop :: Gremlin Archetype ............. SUCCESS [0.280s]
[INFO] Apache TinkerPop :: Archetype - TinkerGraph ....... SUCCESS [8.666s]
[INFO] Apache TinkerPop :: Archetype - Server ............ SUCCESS [13.388s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3:12:10.717s
[INFO] Finished at: Wed Mar 16 00:25:26 MDT 2016
[INFO] Final Memory: 100M/833M
[INFO] ------------------------------------------------------------------------
```

**Comment by okram** [comment]
@twilmes -- it would be great if you reviewed this ticket as it has to do with speed up in `TraverserRequirement` calculations. Perhaps some profiling magic on your side (compared to `master/`) would be possible.

**Comment by spmallette** [comment]
Travis looks like it's failing over an error you fixed for my stuff on TINKERPOP-575. Is that fix not in this branch?

**Comment by okram** [comment]
@spmallette -- I dunno. I ran integration tests over night and they passed. I think Travis is fuggled. It always just fails all the tests.

**Comment by spmallette** [comment]
VOTE +1

**Comment by dkuppitz** [comment]
VOTE: +1

**Pull request merged**
