### PR TITLE
TINKERPOP-1308 Allow Serialization to "reference"

### PR DESCRIPTION
**Pull request by spmallette**
https://issues.apache.org/jira/browse/TINKERPOP-1308

Added a "lite" serializer option for gryo in Gremlin Server. This serializer will write graph elements to "referenced" rather than "detached". The default serialization behavior for Gremlin Server has not changed as a result of this work.  Using the "lite" serialization is not the default, but an option to be made on the request.

Everything is good with:

```text
mvn clean install && mvn verify -pl gremlin-server -DskipIntegrationTests=false
```

VOTE +1

### CODE REVIEW

**Comment by PommeVerte** [comment]
Had a look through the changes. Noticed you add a 'lite' `path` Serializer, does `tree` get serialized properly as well? I kind of expect it to since it leverages `vertex`/`edge` serialization but thought I would double check that with you.

Appart from that one question it's looking tight.

**Comment by spmallette** [comment]
yes - i would expect it to though i don't know that i explicitly tried. as it is implemented at the serializer level, the behavior should apply to graph elements embedded in other objects (like `Tree`). so is that a +1 from you? :)

**Comment by PommeVerte** [comment]
Yeah that's a +1 from me :)

**Comment by dkuppitz** [comment]
VOTE: +1

**Pull request closed without merging**
