### PR TITLE
TINKERPOP3-908 Use line breaks in documentation

### PR DESCRIPTION
**Pull request by spmallette**
This PR isn't ready for VOTE.  I opened this PR more for collaboration.  While all the line breaks have been added, there is a problem in doc generation I can't figure out with: `the-traversal.asciidoc`.  Doc generation is failing there.

@dkuppitz can you please take a look - i'm just not seeing what's wrong.  Once we get the docs generating, we can put this PR up for VOTE

### CODE REVIEW

**Comment by spmallette** [comment]
Aha - this is failing without the line breaks! Switched back to master and still get:

```text
 * source:   /home/smallette/git/apache/incubator-tinkerpop/docs/src/the-traversal.asciidoc
   target:   /home/smallette/git/apache/incubator-tinkerpop/target/postprocess-asciidoc/the-traversal.asciidoc
   progress: [================================================================>                                   ] 64%No such property: keys for class: e
Display stack trace? [yN] g.V().hasLabel('song').out('followedBy').groupCount().by('name').
groovysh_parse: 3: expecting EOF, found ')' @ line 3, column 11.
   f.exists()) f.deleteDir()
```

Anyone know what this is?  please fix in this branch if you know the problem that way we can merge back to master cleanly.

**Comment by okram** [comment]
This worked for me locally. VOTE +1.

**Comment by dkuppitz** [comment]
`the-traversal.asciidoc` also worked for me (I didn't try the others as I still have to set up my Hadoop 2 environment first; will do that the coming weekend). Hence, I can tell that the error mentioned above is not a general problem in the docs, but I can't vote yet.

**Comment by spmallette** [comment]
yeah - i got past that issue - stuck on giraph execution now.  something fishy with my hadoop2 stuff.  this was working for me before - i guess something must have changed in giraph.

**Comment by okram** [comment]
Giraph hasn't changed since the update to 2.0 Hadoop.

**Comment by dkuppitz** [comment]
Not sure if the changes had the desired effect, but the docs can be built fine.

VOTE: +1

**Comment by spmallette** [comment]
Got my docs generating: +1

RESULT: +1 (3) merging.

**Pull request merged**
