### PR TITLE
TINKERPOP3-670 tail step (v2)

### PR DESCRIPTION
**Pull request by mhfrantz**
Replaces PR #60 

Based on feedback on the initial PR:
* correctly (I hope) tested and implemented "bulk" support
* `ComputerVerificationStrategy` balks at mid-traversal global tail steps
* `__` (anonymous traversals) include `tail` methods
* deferred execution during MR (using `Bypassing`)

The hadoop-gremlin tests pass for me.

### CODE REVIEW

**Comment by okram** [comment]
Sweet. Did you make sure `SparkGraphComputer` integration tests pass? If that passes, Giraph will.

**Comment by mhfrantz** [comment]
Yes, I see both SparkGraphComputerProcessIntegrateTest and GiraphGraphComputerProcessIntegrateTest mentioned in the test output.  I'm using the GREMLIN_TESTS env var to run only the `tail` and `range` tests.  Most of them are skipped by `ComputerVerificationStrategy`, but the one that you asked me to add does run on both Spark and Giraph:
```
...
Testing: g_V_repeatXbothX_timesX3X_tailX7X
...
Tests run: 18, Failures: 0, Errors: 0, Skipped: 12, Time elapsed: 24.016 sec - in org.apache.tinkerpop.gremlin.hadoop.process.computer.giraph.GiraphGraphComputerProcessIntegrateTest
...
Testing: g_V_repeatXbothX_timesX3X_tailX7X
...
Tests run: 18, Failures: 0, Errors: 0, Skipped: 12, Time elapsed: 12.464 sec - in org.apache.tinkerpop.gremlin.hadoop.process.computer.spark.SparkGraphComputerProcessIntegrateTest
```
Also, the same selected tinkergraph-gremlin tests still pass.
```
Tests run: 18, Failures: 0, Errors: 0, Skipped: 12, Time elapsed: 1.115 sec - in org.apache.tinkerpop.gremlin.tinkergraph.process.TinkerGraphProcessComputerTest
...
Tests run: 18, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.138 sec - in org.apache.tinkerpop.gremlin.tinkergraph.process.TinkerGraphProcessStandardTest
```

**Comment by mhfrantz** [comment]
@okram Let me know if there's anything else you want on this PR.

**Comment by okram** [comment]
Can you merge master/ into your branch and then provide a PR. I will then merge.

**Comment by mhfrantz** [comment]
@okram Replaced by PR #64

**Pull request closed without merging**
