### PR TITLE
TINKERPOP3-670 tail step (v3)

### PR DESCRIPTION
**Pull request by mhfrantz**
Replaces PR #61 

Rebase to master

### CODE REVIEW

**Comment by okram** [comment]
When I pulled, `GraphTraversal` gets messed up as the `hasNot()` is reintroduced into it. Can you make sure the additions are respective of current master?

**Comment by mhfrantz** [comment]
@okram I don't see the unintentional mods that you mentioned.  I looked at each commit in this PR, as well as the overall file diff.

**Comment by okram** [comment]
Hmm. Okay. I'll figure it out -- doing it now. One thing that you could provide as a separate PR -- update to traversal.asciidoc so we have documentation on `TailXXXStep`.

**Comment by mhfrantz** [comment]
I do see a problem in `ProcessComputerSuite` ... somehow my `import` was dropped.  I'll push a commit to this PR.

**Comment by mhfrantz** [comment]
I would swear that at some point, there were wildcard imports in `ProcessComputerSuite` and `GroovyProcessComputerSuite`.

**Comment by okram** [comment]
There is also a problem with `by(id)` vs. `by(name)` in the Groovy test. I am fixing now. Will push in < 5 minutes. Also, Groovy test is not in the new `TraversalScriptHelper` pattern.

**Comment by mhfrantz** [comment]
Seems to have been merged by @okram

**Pull request closed without merging**
