### PR TITLE
TINKERPOP-958: split .profile() into ProfileSideEffectStep and ProfileStep (which is a MapStep).

### PR DESCRIPTION
**Pull request by rjbriody**
https://issues.apache.org/jira/browse/TINKERPOP-958

I split .profile() into ProfileSideEffectStep and ProfileStep (which is a MapStep).

```.profile()``` emits a TraversalMetrics.
```profile('side effect key')``` stores TraversalMetrics in a side effect.

Tests modified and added.

### CODE REVIEW

**Comment by okram** [comment]
A few things.

1. The name of the test is `ProfileTest.Traversals` not `ProfileSideEffectTest.Traversals`. Its based on the `GraphTraversal.name()`, not the underlying step. Likewise for `GroovyProfileTest.Traversals`. Thus, put all those tests into one test suite. See how there is no `GroupCountSideEffectTest.Traversals`, just `GroupCountTest.Traversals`.

2. Can you provide (as a comment here) the following -- UPGRADE instructions for users and CHANGELOG notes. Don't do it in the code as merging might suck. If you put it here, I can put it in on merge.

3. Can you verify that Giraph/Spark are happy?

Thanks @rjbriody

**Comment by rjbriody** [comment]
1 Done

2
Upgrade Instructions:
The profile()-Step has been refactored into 2 steps - the ProfileStep and the ProfileSideEffectStep. Users who previously used the profile()-Step in conjunction with cap(TraversalMetrics.METRICS_KEY) can now simply omit the cap step. Users who retrieved TraverseralMetrics from the side effects after iteration can still do so, but will need to specify a side effect key when using the profile()-Step.

CHANGELOG
Split existing profile()-Step into ProfileStep and ProfileSideEffectStep. profile()-Step now emits TraversalMetrics without the need for cap()-Step.

3 I'm guessing this is outside the coverage of the tests? I'm not hooked up to run Giraph or Spark (and don't have time to go down that rabbit hole). I could definitely use some help here if testing those is required for merge.

**Comment by okram** [comment]
@rjbriody --- is any of this backwards compatible?

**Comment by rjbriody** [comment]
Nope.

These are the 2 things possible before:
```
t = g.V().profile()
t.iterate()
metrics = t.asAdmin().getSideEffects().get(TraversalMetrics.METRICS_KEY).get()
```
or
```
g.V().profile().cap(TraversalMetrics.METRICS_KEY)
```

Neither of which behave the same way now.

**Comment by okram** [comment]
```
Failed tests:
  GroovyProfileTest$Traversals>ProfileTest.g_V_hasXinXcreatedX_count_isX1XX_valuesXnameX_profileXmetrics_keyX:358->ProfileTest.validate_g_V_hasXinXcreatedX_count_isX1XX_valuesXnameX_profile:322 There should be 3 top-level metrics. expected:<3> but was:<0>
  GroovyProfileTest$Traversals>ProfileTest.g_V_hasXinXcreatedX_count_isX1XX_valuesXnameX_profile:346->ProfileTest.validate_g_V_hasXinXcreatedX_count_isX1XX_valuesXnameX_profile:322 There should be 3 top-level metrics. expected:<3> but was:<0>
  ProfileTest$Traversals>ProfileTest.g_V_hasXinXcreatedX_count_isX1XX_valuesXnameX_profileXmetrics_keyX:358->ProfileTest.validate_g_V_hasXinXcreatedX_count_isX1XX_valuesXnameX_profile:322 There should be 3 top-level metrics. expected:<3> but was:<0>
  ProfileTest$Traversals>ProfileTest.g_V_hasXinXcreatedX_count_isX1XX_valuesXnameX_profile:346->ProfileTest.validate_g_V_hasXinXcreatedX_count_isX1XX_valuesXnameX_profile:322 There should be 3 top-level metrics. expected:<3> but was:<0>

Tests in error:
  GroovyProfileTest$Traversals>ProfileTest.g_V_out_out_profile_modern:156->ProfileTest.validate_g_V_out_out_profile_modern:138 » NullPointer
  GroovyProfileTest$Traversals>ProfileTest.g_V_out_out_profile_modernXmetrics_keyX:166->ProfileTest.validate_g_V_out_out_profile_modern:138 » NullPointer
  ProfileTest$Traversals>ProfileTest.g_V_out_out_profile_modern:156->ProfileTest.validate_g_V_out_out_profile_modern:138 » NullPointer
  ProfileTest$Traversals>ProfileTest.g_V_out_out_profile_modernXmetrics_keyX:166->ProfileTest.validate_g_V_out_out_profile_modern:138 » NullPointer
```

Just right click on `SparkGraphComputerProcessIntegrateTest` and hit "run" (IntelliJ). It runs very fast -- less than 30 seconds.

**Comment by rjbriody** [comment]
Spark tests pass. 
```
mvn clean install verify -DskipIntegrationTests=false
```
...running locally, but could be a while. CI may finish first.

**Comment by okram** [comment]
VOTE +1.

**Comment by rjbriody** [comment]
```mvn clean install verify -DskipIntegrationTests=false```
just finished successfully on my machine as well.

**Comment by okram** [comment]
When this gets merged, I will handle getting it to work with the `Memory` model in https://github.com/apache/incubator-tinkerpop/pull/243 .. will be a good test to see how easy it is for people who have MapReduce-based steps (basically no one) to convert to `MemoryComputeKey`.

**Comment by dkuppitz** [comment]
VOTE: +1

**Comment by spmallette** [comment]
i don't see any changes to docs here.  I assume at minimum "upgrade docs" are needed especially since this is a breaking change. @okram will you handle that on merge?

VOTE +1 assuming the addition of docs

**Comment by rjbriody** [comment]
I left upgrade and changelog notes above: https://github.com/apache/incubator-tinkerpop/pull/242#issuecomment-188858152

...but you just made me remember that the docs for Profile Step need to be updated as well. @okram, should I make those in place as part of this PR or provide notes for what to change?

**Comment by rjbriody** [comment]
Docs have been updated but I can't process them because I don't have Hadoop running so I only did a dry run.

**Comment by okram** [comment]
I will handle the merge and docs.

**Comment by okram** [comment]
This work has been merged into TINKERPOP-1192 branch. When that branch gets merged to master/, I will close this ticket.

**Pull request merged**
