### PR TITLE
TINKERPOP-1179

### PR DESCRIPTION
**Pull request by velo**
Archetypes modules won't compile
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:2.4:integration-test (default) on project gremlin-archetype-tinkergraph: 
[ERROR] Archetype IT 'standard' failed: Cannot run additions goals. 
[ERROR] -> [Help 1] 
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archety
```

Due to https://issues.apache.org/jira/browse/ARCHETYPE-488

workaround is to run using maven 3.2

### CODE REVIEW

**Comment by spmallette** [comment]
Thanks for this.  i merged it to the TINKERPOP-1179 branch. In that branch i change the build target to `mvn clean install`. We should see failures on that branch going forward.  When we get green we can try to merge back to tp31 again.

**Comment by spmallette** [comment]
here's the build for that TINKERPOP-1179 branch:

https://ci.appveyor.com/project/ApacheSoftwareFoundation/incubator-tinkerpop/build/226

Looks like the problem is still with that timing issue with the hadoop tests

```text
g_V_sideEffectXThread_sleepX10XX_sideEffectXThread_sleepX5XX_profile(org.apache.tinkerpop.gremlin.process.traversal.step.sideEffect.ProfileTest$Traversals)  Time elapsed: 0.281 sec  <<< FAILURE!
java.lang.AssertionError: Duration should be at least the length of the sleep (59ms): 53
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.apache.tinkerpop.gremlin.process.traversal.step.sideEffect.ProfileTest.g_V_sideEffectXThread_sleepX10XX_sideEffectXThread_sleepX5XX_profile(ProfileTest.java:173)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.tinkerpop.gremlin.process.GremlinProcessRunner.runChild(GremlinProcessRunner.java:53)
	at org.apache.tinkerpop.gremlin.process.GremlinProcessRunner.runChild(GremlinProcessRunner.java:37)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.apache.tinkerpop.gremlin.AbstractGremlinSuite.runChild(AbstractGremlinSuite.java:212)
	at org.apache.tinkerpop.gremlin.AbstractGremlinSuite.runChild(AbstractGremlinSuite.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

Still not quite sure the best way to fix this.

**Comment by velo** [comment]
I was reading this test, and it promises "6 elements w/ a 10ms sleep each = 60ms with 10ms for other computation.", so, should be 60ms (for the 6 elements) + 10ms (for other stuff) = 70 ms.

I wonder why the assertion is >= 59 and not >= 70

**Comment by spmallette** [comment]
@rjbriody i know you're sick of this damn test and probably just want to obliterate it, but can you provide any explanation for @velo ?

we could mark this test as "nondeterministic" which is a class of tests we have that are kinda fishy, rely on timing of things, etc.  but i think it would be best to use that only as a last resort.

**Comment by rjbriody** [comment]
np @spmallette, anything for you buddy!


> 6 elements w/ a 10ms sleep each = 60ms with 10ms for other computation.

This comment (and others like it from a few other tests) are from when we actually attempted to impose an upper bound on the duration. The assert used to verify that the duration was greater than the total sleep time AND less than whatever that was + 10ms. That was totally unreliable even after we jacked the tolerance so I just got rid of all the upper bound checking. So I thought "Hey, it should at least take as long as all the sleeps because that's dependable... right?". Guess not??? So this failure is particularly weird. There's no reason I can think of why the duration could possibly be less than the minimum.

**Comment by velo** [comment]
@rjbriody so, taking even less time on a crowed server shouldn't happen, right?

but looks like it does =(

**Comment by rjbriody** [comment]
It's as if the laws of traversal execution and Thread.sleep have ceased to exist.

**Comment by velo** [comment]
lol

And is there any other assertion besides time we could do that would be more meaningful?

**Comment by rjbriody** [comment]
We already also check all the counts but I mean, these are the profile tests. Duration is kinda the star of the show.

**Comment by spmallette** [comment]
not sure if this is just a temporary error or not but we're seeing this error over and over from appveyor: https://ci.appveyor.com/project/ApacheSoftwareFoundation/incubator-tinkerpop/build/291

**Comment by velo** [comment]
image
seems chocolatey is down

**Comment by pluradj** [comment]
Seems like this would be a better solution -- setting a dependency for `maven-invoker` on the `maven-archetype-plugin` -- since you wouldn't be bound to a specific version of Maven 3. https://issues.apache.org/jira/browse/ARCHETYPE-488?focusedCommentId=14731166&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14731166

**Comment by spmallette** [comment]
I just rebased TINKERPOP-1179 on tp31 - i don't imagine anything would have changed in the build, but it's running now:

https://ci.appveyor.com/project/ApacheSoftwareFoundation/incubator-tinkerpop/build/634

How should we proceed with this? should we target PRs for this issue at the TINKERPOP-1179 branch going forward and close this PR?

**Comment by spmallette** [comment]
Since no one has any opinions since my last comment, I think we should just close this and target future PRs at the TINKERPOP-1179 which I will synch with tp31 periodically. I will lose this PR.

@pluradj you posted a comment here on 3/10 for a "better solution". if you intend to implement, just submit the PR against TINKERPOP-1179 (or commit directly i guess since the branch is on the TinkerPop side)

**Pull request closed without merging**
