### PR TITLE
TINKERPOP-1033: Store sideEffects as a persisted RDD

### PR DESCRIPTION
**Pull request by okram**
https://issues.apache.org/jira/browse/TINKERPOP-1033

This is a massive amount of work. Just making sideEffects be stored as persisted RDDs led to a swath of other updates. Here is the list of things:

* It is now possible for Spark users to completely avoid using HDFS -- they simply use `PersistedInputRDD` and `PersistedOutputRDD` for everything.
* Added a significant amount of testing to ensure that persisted RDDs work as expected in all situations.
* `InputRDD`s now have a `readMemoryRDD()` method which handles reading sideEffects (i.e. memory).
* `OutputRDD`s now have a `writeMemoryRDD()` method which handles writing sideEffects (i.e. memory).
* There is a `Storage` interface in gremlin-core which providers can implement to have "file-system semantics" for their data source. HDFS and Spark both implement it. No more Groovy meta-programming for HDFS! Sweeeeet.
* With `Storage` all the file management in both Spark and Giraph is much simpler as the methods in `Storage` allowed me to gut alot of (error prone) code.
* There is a general test suite which makes sure both HDFS and Spark storage behave "the same."
* Updated documentation, upgrade docs, and added JavaDoc to `Storage`.
* The docs for `BulkLoaderVertexProgram` and Spark/Giraph uses a `data/` directory. It wasn't consistent with our other examples so I cleaned it up.
* Fixed a minor bug in `ClusterCountMapReduce`.
* Cleaned up how HDFS data is streamed -- its pure now, based solely on `InputFormat` behavior (I learned something new in Hadoop).
* There are a few minor "breaking changes" around `hdfs.methods()`. They are "ok" as HDFS interaction prior to this moment  has always been manual via the Gremlin Console.

I updated the "update" docs:

http://tinkerpop.apache.org/docs/3.1.1-SNAPSHOT/upgrade/#_storage_i_o

I updated the "reference" docs:

http://tinkerpop.apache.org/docs/3.1.1-SNAPSHOT/reference/#_storage_systems

You can see the JavaDoc for the new `Storage` interface:

http://tinkerpop.apache.org/javadocs/3.1.1-SNAPSHOT/core/org/apache/tinkerpop/gremlin/structure/io/Storage.html

I ran integration tests and built and deployed docs successfully. 
  
VOTE +1.

### CODE REVIEW

**Comment by okram** [comment]
Integration test `BUILD SUCCESSFUL`.

```
[INFO] Apache TinkerPop .................................. SUCCESS [4.800s]
[INFO] Apache TinkerPop :: Gremlin Shaded ................ SUCCESS [2.300s]
[INFO] Apache TinkerPop :: Gremlin Core .................. SUCCESS [34.224s]
[INFO] Apache TinkerPop :: Gremlin Test .................. SUCCESS [11.772s]
[INFO] Apache TinkerPop :: Gremlin Groovy ................ SUCCESS [32.672s]
[INFO] Apache TinkerPop :: Gremlin Groovy Test ........... SUCCESS [6.828s]
[INFO] Apache TinkerPop :: TinkerGraph Gremlin ........... SUCCESS [3:22.133s]
[INFO] Apache TinkerPop :: Hadoop Gremlin ................ SUCCESS [5:02.151s]
[INFO] Apache TinkerPop :: Spark Gremlin ................. SUCCESS [4:03.723s]
[INFO] Apache TinkerPop :: Giraph Gremlin ................ SUCCESS [2:01:35.469s]
[INFO] Apache TinkerPop :: Neo4j Gremlin ................. SUCCESS [18:06.653s]
[INFO] Apache TinkerPop :: Gremlin Driver ................ SUCCESS [10.940s]
[INFO] Apache TinkerPop :: Gremlin Server ................ SUCCESS [11:13.160s]
[INFO] Apache TinkerPop :: Gremlin Console ............... SUCCESS [1:10.880s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2:46:18.192s
[INFO] Finished at: Wed Jan 06 19:01:26 MST 2016
[INFO] Final Memory: 103M/708M
```

**Comment by dkuppitz** [comment]
* `mvn clean install`: passed
* integration tests: passed
* `bin/process-docs.sh`: passed

VOTE: +1

**Comment by spmallette** [comment]
This PR drops a few "internal" classes - folks shouldn't have been using those directly, but would it have been better to deprecate those as opposed to just removing completely?  

Seems like deprecation would have worked for:

* [HadoopLoader](https://github.com/apache/incubator-tinkerpop/pull/192/files#diff-* 55e3610726b342e666b34223b8270526)
* [HDFSTools](https://github.com/apache/incubator-tinkerpop/pull/192/files#diff-88ec5bbe9a2817117d62799b9e91a20a)
* [SparkLoader](https://github.com/apache/incubator-tinkerpop/pull/192/files#diff-0c5aa03b09c929fa6440edb9bacc7e76)

even though these are pretty low-level classes, it would be nice to stick to "not breaking (even if they are doing stuff they are not supposed to)" plan imo.

**Comment by okram** [comment]
Here is the thing. `SparkLoader` was introduced in 3.1.1-SNAPSHOT :D so it okay to drop. `HadoopLoader` is all meta-programming Groovy stuff to get ls(), rm(), etc. to work in Gremlin Console. We can keep the the class, but we can't have it loaded else it will interfere with the new `FileSystemStorage`. However, I say we just drop it. Its so low level and all meta-programmy that if someone is using it, they are retarded.

Finally, `HDFSTools`. Again, low level.... I can bring that class back, but people really shouldn't be using it. This is like an internal utility and so specific to TinkerPop filesystem stuff. ??

**Comment by spmallette** [comment]
Yeah - they shouldn't be using them, but we know how that goes....make a class public and someone is gonna use it to their detriment or otherwise.  anyway, i'd say just do one of the following then:

1. bring them back and deprecate
2. add something to upgrade docs to explain their removal - you already have the section - perhaps just a WARNING that explicitly mentions the classes.

**Comment by spmallette** [comment]
VOTE: +1

**Pull request merged**
