### PR TITLE
TINKERPOP-1305: HALTED_TRAVERSERS hold wrong information

### PR DESCRIPTION
**Pull request by okram**
https://issues.apache.org/jira/browse/TINKERPOP-1305

@dkuppitz found a severe bug in 3.2.0 in OLAP traversal chains. Interestingly enough, all the test cases we had didn't touch this problem (even though they did tangentially, but didn't test particular expectations). As such, two new tests have been added to `pageRank()` and `peerPressure()` which demonstrate the problem has been rectified.

CHANGELOG

```
* Fixed a severe bug around halted traversers in a multi-job OLAP traversal chain.
* Ensure a separation of `GraphComputer` and `VertexProgram` configurations in `SparkGraphComputer` and `GiraphGraphComputer`.
* `PeerPressureVertexProgram` now supports dynamic initial vote strength calculations.
* Added `EmptyMemory` for ease of use when no memory exists.
* Updated `VertexComputing.generateProgram()` API to include `Memory` (*breaking*).
* `ImmutablePath.TailPath` is now serializable like `ImmutablePath`.
```

UPGRADE

```
VertexComputing API Change
+++++++++++++++++++++++

The `VertexComputing` API is used by steps that wrap a `VertexProgram`. There is a method called `VertexComputing.generateProgram()` that has changed which now takes a second argument of `Memory`. To  upgrade, simply fix the method signature of your `VertexComputing` implementations. The `Memory` argument can be safely ignored to effect the exact same semantics as prior. However, now previous OLAP job `Memory` can be leveraged when constructing the next `VertexProgram` in an OLAP traversal chain.
```

`mvn clean install` PASSED, integration tests PASSED, and docs built GOOD.

```
[INFO] Apache TinkerPop .................................. SUCCESS [4.477s]
[INFO] Apache TinkerPop :: Gremlin Shaded ................ SUCCESS [2.256s]
[INFO] Apache TinkerPop :: Gremlin Core .................. SUCCESS [38.899s]
[INFO] Apache TinkerPop :: Gremlin Test .................. SUCCESS [11.399s]
[INFO] Apache TinkerPop :: Gremlin Groovy ................ SUCCESS [38.721s]
[INFO] Apache TinkerPop :: Gremlin Groovy Test ........... SUCCESS [6.730s]
[INFO] Apache TinkerPop :: TinkerGraph Gremlin ........... SUCCESS [3:15.097s]
[INFO] Apache TinkerPop :: Gremlin Benchmark ............. SUCCESS [5.194s]
[INFO] Apache TinkerPop :: Hadoop Gremlin ................ SUCCESS [10:57.415s]
[INFO] Apache TinkerPop :: Spark Gremlin ................. SUCCESS [6:28.472s]
[INFO] Apache TinkerPop :: Giraph Gremlin ................ SUCCESS [2:47:11.903s]
[INFO] Apache TinkerPop :: Neo4j Gremlin ................. SUCCESS [1:08:16.166s]
[INFO] Apache TinkerPop :: Gremlin Driver ................ SUCCESS [8.704s]
[INFO] Apache TinkerPop :: Gremlin Server ................ SUCCESS [13:13.317s]
[INFO] Apache TinkerPop :: Gremlin Console ............... SUCCESS [1:23.504s]
[INFO] Apache TinkerPop :: Gremlin Archetype ............. SUCCESS [0.134s]
[INFO] Apache TinkerPop :: Archetype - TinkerGraph ....... SUCCESS [7.257s]
[INFO] Apache TinkerPop :: Archetype - Server ............ SUCCESS [11.883s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4:33:02.004s
[INFO] Finished at: Thu May 19 00:09:24 MDT 2016
[INFO] Final Memory: 99M/712M
[INFO] ------------------------------------------------------------------------
```

VOTE +1.

### CODE REVIEW

**Comment by okram** [comment]
This also solves https://issues.apache.org/jira/browse/TINKERPOP-1298

**Comment by spmallette** [comment]
Can you rename this PR? You transposed the number and the wrong JIRA ticket is getting the updates.

**Comment by spmallette** [comment]
VOTE +1 - `$ docker/build.sh -t -i -n` is all good

**Comment by dkuppitz** [comment]
Even if this PR gets another +1, please don't merge yet, as I'm still doing lots of manual tests these days. I'm still not sure if I like halted traversers being stored in the config (simply because I'm not yet at the point where I've tested this particular change).

And even if my tests are going to run smoothly, I'm still worried about how scalable this approach is. In a distributed environment, how is the configuration distributed between worker iterations? Where is it stored? Will it be (re)loaded for each worker iteration? If so, how long does it take to load a config that holds millions of halted traversers?

**Comment by okram** [comment]
These are "master traversal" traversers. Even before when it was stored in sideeffects, those are ultimately stored in `Configuration` (`TRAVERSAL`). Its the same scalability as before, just better semantics as we shouldn't store halted traversers as side-effects (they have "left the traversal"). Finally, since the beginning, OLAP reductions to the master traversal are only as scalable as the single machine it comes back to. Thus, groups(), limits(), groupCounts(), sums(), etc. are important. There is no `g.V()` on a billion vertex graph and stream back results.

**Comment by dkuppitz** [comment]
Dozens of manual tests later...

VOTE: +1

**Pull request merged**
