### PR TITLE
TINKERPOP-1041

### PR DESCRIPTION
**Pull request by velo**
Same as https://github.com/apache/incubator-tinkerpop/pull/207

But target on tp31

### CODE REVIEW

**Comment by spmallette** [comment]
@velo do you have thoughts on how to proceed with windows CI now that we know apache infra doesn't currently support that?

**Comment by velo** [comment]
I guess we would maintain the status quo.

May be a committer can enable an appveyor free account

>

**Comment by spmallette** [comment]
Apache administers the github mirror so they would have to enable the commit hook to appveyor unless i'm missing something in how appveyor works.  I assume you can only enabled appveyor on a github repo you administer (like travis).  is that right?

**Comment by velo** [comment]
You probably right

**Comment by spmallette** [comment]
I guess you should update the PR to remove the appveyor stuff then.  

@pluradj have you had a look at this PR yet?  would be nice to get your review/vote as you have a windows environment that you could test it out on...

**Comment by pluradj** [comment]
I'm running into some test failures when I do `mvn clean install` on Windows. I built on Linux and Mac without running into this.

```
Tests run: 9, Failures: 2, Errors: 2, Skipped: 0, Time elapsed: 37.053 sec <<< FAILURE! - in org.apache.tinkerpop.gremli
n.spark.SparkHadoopGremlinTest
shouldSupportRemoveAndListMethods(org.apache.tinkerpop.gremlin.hadoop.structure.io.FileSystemStorageCheck)  Time elapsed
: 1.498 sec  <<< FAILURE!
java.lang.AssertionError: expected:<2> but was:<3>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at org.apache.tinkerpop.gremlin.hadoop.structure.io.AbstractStorageCheck.checkRemoveAndListMethods(AbstractStora
geCheck.java:84)
        at org.apache.tinkerpop.gremlin.hadoop.structure.io.FileSystemStorageCheck.shouldSupportRemoveAndListMethods(Fil
eSystemStorageCheck.java:58)

shouldNotHaveResidualDataInStorage(org.apache.tinkerpop.gremlin.hadoop.structure.io.FileSystemStorageCheck)  Time elapse
d: 1.372 sec  <<< FAILURE!
java.lang.AssertionError: null
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertFalse(Assert.java:64)
        at org.junit.Assert.assertFalse(Assert.java:74)
        at org.apache.tinkerpop.gremlin.hadoop.structure.io.AbstractStorageCheck.checkResidualDataInStorage(AbstractStor
ageCheck.java:133)
        at org.apache.tinkerpop.gremlin.hadoop.structure.io.FileSystemStorageCheck.shouldNotHaveResidualDataInStorage(Fi
leSystemStorageCheck.java:78)

shouldSupportCopyMethods(org.apache.tinkerpop.gremlin.hadoop.structure.io.FileSystemStorageCheck)  Time elapsed: 0.702 s
ec  <<< ERROR!
java.util.concurrent.ExecutionException: org.apache.hadoop.mapred.FileAlreadyExistsException: Output directory C:/home/p
luradj/src/github/apache/incubator-tinkerpop/TINKERPOP-1041/spark-gremlin/target/test-case-data/SparkHadoopGraphProvider
/graph-provider-data/clusterCount already exists
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
        at org.apache.tinkerpop.gremlin.hadoop.structure.io.AbstractStorageCheck.checkCopyMethods(AbstractStorageCheck.j
ava:109)
        at org.apache.tinkerpop.gremlin.hadoop.structure.io.FileSystemStorageCheck.shouldSupportCopyMethods(FileSystemSt
orageCheck.java:69)
Caused by: org.apache.hadoop.mapred.FileAlreadyExistsException: Output directory C:/home/pluradj/src/github/apache/incub
ator-tinkerpop/TINKERPOP-1041/spark-gremlin/target/test-case-data/SparkHadoopGraphProvider/graph-provider-data/clusterCo
unt already exists
        at org.apache.hadoop.mapreduce.lib.output.FileOutputFormat.checkOutputSpecs(FileOutputFormat.java:146)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1.apply$mcV$sp(PairRDDFunctions.scal
a:1011)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1.apply(PairRDDFunctions.scala:998)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1.apply(PairRDDFunctions.scala:998)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:310)
        at org.apache.spark.rdd.PairRDDFunctions.saveAsNewAPIHadoopDataset(PairRDDFunctions.scala:998)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopFile$2.apply$mcV$sp(PairRDDFunctions.scala:9
38)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopFile$2.apply(PairRDDFunctions.scala:930)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopFile$2.apply(PairRDDFunctions.scala:930)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:310)
        at org.apache.spark.rdd.PairRDDFunctions.saveAsNewAPIHadoopFile(PairRDDFunctions.scala:930)
        at org.apache.spark.api.java.JavaPairRDD.saveAsNewAPIHadoopFile(JavaPairRDD.scala:809)
        at org.apache.tinkerpop.gremlin.spark.structure.io.OutputFormatRDD.writeMemoryRDD(OutputFormatRDD.java:65)
        at org.apache.tinkerpop.gremlin.spark.process.computer.SparkGraphComputer.lambda$submitWithExecutor$1(SparkGraph
Computer.java:271)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

shouldSupportHeadMethods(org.apache.tinkerpop.gremlin.hadoop.structure.io.FileSystemStorageCheck)  Time elapsed: 0.032 s
ec  <<< ERROR!
java.io.IOException: Unable to delete file: C:\home\pluradj\src\github\apache\incubator-tinkerpop\TINKERPOP-1041\spark-g
remlin\target\test-case-data\SparkHadoopGraphProvider\graph-provider-data\~reducing\part-r-00001
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2279)
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653)
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535)
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270)
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653)
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535)
        at org.apache.tinkerpop.gremlin.hadoop.structure.io.FileSystemStorageCheck.deleteDirectory(FileSystemStorageChec
k.java:101)
        at org.apache.tinkerpop.gremlin.hadoop.structure.io.FileSystemStorageCheck.shouldSupportHeadMethods(FileSystemSt
orageCheck.java:49)

Running org.apache.tinkerpop.gremlin.spark.structure.io.InputOutputRDDTest
[WARN] org.apache.tinkerpop.gremlin.hadoop.process.computer.AbstractHadoopGraphComputer$Features - Unknown OutputFormat
class and thus, persistence options are unknown -- assuming all options are possible
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.346 sec - in org.apache.tinkerpop.gremlin.spark.struct
ure.io.InputOutputRDDTest
Running org.apache.tinkerpop.gremlin.spark.structure.io.InputRDDTest
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.933 sec <<< FAILURE! - in org.apache.tinkerpop.gremlin
.spark.structure.io.InputRDDTest
shouldReadFromArbitraryRDD(org.apache.tinkerpop.gremlin.spark.structure.io.InputRDDTest)  Time elapsed: 3.224 sec  <<< E
RROR!
java.lang.IllegalStateException: org.apache.hadoop.mapred.FileAlreadyExistsException: Output directory C:/home/pluradj/s
rc/github/apache/incubator-tinkerpop/TINKERPOP-1041/spark-gremlin/target/test-case-data/InputRDDTest/shouldReadFromArbit
raryRDD/~reducing already exists
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
        at org.apache.tinkerpop.gremlin.process.computer.traversal.step.map.ComputerResultStep.processNextStart(Computer
ResultStep.java:80)
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:126)
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:37)
        at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.next(DefaultTraversal.java:157)
        at org.apache.tinkerpop.gremlin.spark.structure.io.InputRDDTest.shouldReadFromArbitraryRDD(InputRDDTest.java:56)

Caused by: org.apache.hadoop.mapred.FileAlreadyExistsException: Output directory C:/home/pluradj/src/github/apache/incub
ator-tinkerpop/TINKERPOP-1041/spark-gremlin/target/test-case-data/InputRDDTest/shouldReadFromArbitraryRDD/~reducing alre
ady exists
        at org.apache.hadoop.mapreduce.lib.output.FileOutputFormat.checkOutputSpecs(FileOutputFormat.java:146)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1.apply$mcV$sp(PairRDDFunctions.scal
a:1011)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1.apply(PairRDDFunctions.scala:998)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1.apply(PairRDDFunctions.scala:998)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:310)
        at org.apache.spark.rdd.PairRDDFunctions.saveAsNewAPIHadoopDataset(PairRDDFunctions.scala:998)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopFile$2.apply$mcV$sp(PairRDDFunctions.scala:9
38)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopFile$2.apply(PairRDDFunctions.scala:930)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopFile$2.apply(PairRDDFunctions.scala:930)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:310)
        at org.apache.spark.rdd.PairRDDFunctions.saveAsNewAPIHadoopFile(PairRDDFunctions.scala:930)
        at org.apache.spark.api.java.JavaPairRDD.saveAsNewAPIHadoopFile(JavaPairRDD.scala:809)
        at org.apache.tinkerpop.gremlin.spark.structure.io.OutputFormatRDD.writeMemoryRDD(OutputFormatRDD.java:65)
        at org.apache.tinkerpop.gremlin.spark.process.computer.SparkGraphComputer.lambda$submitWithExecutor$1(SparkGraph
Computer.java:271)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

Travis seems happy, so it's something in my environment?

```
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T07:57:37-04:00)
Maven home: C:\home\pluradj\usr\lib\apache-maven-3.3.3\bin\..
Java version: 1.8.0_66, vendor: Oracle Corporation
Java home: C:\home\pluradj\usr\lib\jdk1.8.0_66\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"
```

**Comment by velo** [comment]
Yes, I was not able to fix this errors.

But if you run either master or tp311, more will fail

**Comment by pluradj** [comment]
You're right, fair enough.
Did you pull the TP3 codebase into Eclipse and run the tests within it?
The code changes look good to me.

**Comment by velo** [comment]
Yes, they also fail on eclipse

**Comment by pluradj** [comment]
I was referring to the testcases from the JIRA... do those now work in Eclipse?

**Comment by velo** [comment]
Ow, i never tried to run all tests in eclipse...

**Comment by velo** [comment]
@spmallette I just asked apache infra for it.
https://issues.apache.org/jira/browse/INFRA-11249

Hopefully we will get that working.

**Comment by velo** [comment]
BTW, @pluradj  any idea on what to do on the broken tests?

**Comment by spmallette** [comment]
@velo thanks for getting appveyor enabled - the process described to me for doing that didn't seem as if it would be that simple - cool

**Comment by pluradj** [comment]
@velo I've been digging around on it. Haven't figured anything out yet.

**Comment by pluradj** [comment]
+1 on appveyor enablement

**Comment by spmallette** [comment]
Perhaps we should re-calibrate a bit here. The original ticket was about getting the `StructureStandardTestSuite` working on windows (which can be a blocker for graph providers doing dev on windows).  As far as i can gather, that much is fixed.  As a bonus, @velo got us a build on windows through appveyor and even got apache infra to enable it for us.

There are some good fixes in this PR as-is and it would be nice to see appveyors yaml in the main dev branches.  Since the original issue is resolved, let's get this PR up for VOTE.  To do that, we need appveyor yaml to change slightly so that it doesn't fail the build.  Since the tests don't all pass, @velo can you please change the build to `-Dspark-gremlin.skip.tests=true` or maybe even skip just the failing tests `-Dspark-gremlin.test.excludes="**/*ExcludeTest.java` - we do that temporarily until a separate pull request can address those failures (we'll need a new ticket obviously).

Does that sound reasonable?

**Comment by pluradj** [comment]
@spmallette sounds ok to me. I have a couple small fixes figured out, but I'm suspecting that the local Spark job is holding on to file handles, which prevents it from deleting files.

Vote: +1. Nice work @velo!

**Comment by velo** [comment]
@spmallette @pluradj done, I create a appveyor profile which skips the broken tests

**Comment by spmallette** [comment]
Looks like appveyor still isn't happy for some reason.....build failed on spark apparently.  @velo as soon as you can get that build to go green we can dig deeper on review/VOTE. thanks.

**Comment by velo** [comment]
> GryoSerializerIntegrateTest.shouldHaveAllRegisteredGryoSerializerClasses:53 � OutOfMemory 

Ouch, will skip this one ass well!

**Comment by velo** [comment]
Done

**Comment by velo** [comment]
Any news on this?

**Comment by spmallette** [comment]
ah - sorry - just got a little busy on other things. we should get this over to tp31.  @pluradj can you please vote on this from the windows perspective?

I'll vote before end of week - then we just need one more....hopefully we close out by end of week.

**Comment by pluradj** [comment]
I voted +1 a few days ago.

The changes for appveyor since then look fine too. I added a windows profile in the `spark-gremlin/pom.xml` to exclude the same tests as appveyor, `mvn clean install` on a local Windows build. I tested with Windows 7.

```
mvn clean install
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Apache TinkerPop ................................... SUCCESS [ 12.979 s]
[INFO] Apache TinkerPop :: Gremlin Shaded ................. SUCCESS [  5.288 s]
[INFO] Apache TinkerPop :: Gremlin Core ................... SUCCESS [ 45.655 s]
[INFO] Apache TinkerPop :: Gremlin Test ................... SUCCESS [ 20.554 s]
[INFO] Apache TinkerPop :: Gremlin Groovy ................. SUCCESS [01:10 min]
[INFO] Apache TinkerPop :: Gremlin Groovy Test ............ SUCCESS [ 11.831 s]
[INFO] Apache TinkerPop :: TinkerGraph Gremlin ............ SUCCESS [01:58 min]
[INFO] Apache TinkerPop :: Hadoop Gremlin ................. SUCCESS [07:21 min]
[INFO] Apache TinkerPop :: Spark Gremlin .................. SUCCESS [01:12 min]
[INFO] Apache TinkerPop :: Giraph Gremlin ................. SUCCESS [ 16.402 s]
[INFO] Apache TinkerPop :: Neo4j Gremlin .................. SUCCESS [  8.352 s]
[INFO] Apache TinkerPop :: Gremlin Driver ................. SUCCESS [ 13.021 s]
[INFO] Apache TinkerPop :: Gremlin Server ................. SUCCESS [ 12.301 s]
[INFO] Apache TinkerPop :: Gremlin Console ................ SUCCESS [ 22.349 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14:31 min
[INFO] Finished at: 2016-02-18T14:46:07-05:00
[INFO] Final Memory: 148M/2211M
[INFO] ------------------------------------------------------------------------
```

**Comment by spmallette** [comment]
oh - thanks @pluradj - i must have missed your vote.

I'm going to run the full integration tests on ubuntu just to be sure nothing is busted there.  I assume that since we still don't have a complete build for windows with `mvn clean install` there would be problems with integration tests in that environment.  If the tests all pass on my end I think this should be good to go.

**Comment by velo** [comment]
FWIW, I would skip broken tests on Windows... is more likely to someone fix
them if they were broken :)

>

**Comment by Alan47** [comment]
You can't be serious velo, right? I originally reported that bug. The test suite is effectively the specification for TinkerPop vendors. That's a good thing in and on itself, but it also means that it must be as clean and polished as it can possibly be. Believe me, the VERY LAST thing you want to do as a TinkerPop vendor is to go in and fix a broken test. It would be analoguous to changing the system specification while implementing the system. The suite needs to be reliable, without any other formal specification, there's no way around it.

**Comment by velo** [comment]
sorry, misspelled... I mean to say "I would**n't** skip broken tests on windows"

**Comment by MartinHaeusler** [comment]
Oh ok, alright then :)

**Comment by spmallette** [comment]
i was working on the assumption that the tests skipped would get a fresh JIRA ticket to track the change.  In my mind, having the core of tinkerpop building on windows with _most_ tests working was better than not having anything at all - which is where we are now on tp31 and master.

**Comment by velo** [comment]
agreed, that is why I created an appveyor profile... which skips this tests...

But I wouldn't create a windows profile.... the idea being this broken tests should be a pain for windows devs (like me)

**Comment by spmallette** [comment]
I've grown suspicious of this line:

https://github.com/apache/incubator-tinkerpop/pull/209/files#diff-8ae08149638a77bbb943e6bb8438cfb6R631

because you `awaitTermination` without calling `shutdown` first. Calling `shutdownNow` after it doesn't indicate an orderly shutdown either and nothing is done with the list of returned un-executed tasks....

that said, I don't think it really matters though because we actually got that test much more stable on the `tp31` line since you originally branched this.  I just wanted to bring those points to your attention in case you had comments.  When I merge your branch to tp31 locally, those lines you added go away.

I had some failures with integration tests last night, but solved the problem this morning (bug in the latest tp31 branch).  I'll need to re-run the tests gain in full tonight after that fix. If all works, I can vote positively tomorrow.

**Comment by velo** [comment]
The way it was before, I would see intermittent errors on windows.

AwaitTermination will "Blocks until all tasks have completed execution after a shutdown request, or the timeout occurs, or the current thread is interrupted, whichever happens first."

So, it will either return after timeout or well all finish.
Them it runs a forcefully shutdown.

That way this tests become stable either here or in the appveyor.

**Comment by spmallette** [comment]
You quoted the javadoc there and that's precisely my point about something looking wrong.  If my interpretation of that javadoc and the java source code is correct, `awaitTermination` is returning false after blocking (due to timeout), and you are just sleeping the thread for 30 seconds. which is plenty of time for that work to finish. then you call a hard `shutdownNow` which has no effect really because there are no more tasks executed. `awaitTermintation` requires a call to `shutdown` somewhere for it to ever return true (success).

if this was a problem for appveyor I suggest you update your branch with the latest changes which should have fixed the problems we were seeing with this test:

https://github.com/apache/incubator-tinkerpop/blob/tp31/gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/engine/GremlinExecutorTest.java#L634-L638

Let's see if appveyor is happy with that change before we go to merge this.

**Comment by velo** [comment]
@spmallette rebased my pull request with tp31, all green!

**Comment by spmallette** [comment]
VOTE +1

**Comment by dkuppitz** [comment]
I cant test in a windows environment, but given the comments in this discussion and a manual review of changes, it all seems to be good.

VOTE: +1

**Comment by spmallette** [comment]
merged - @velo thanks for working through this with us. it would be great if you could add a JIRA ticket for any remaining issues we have with this (e.g. tests we ignored for purpose of getting this merged back to master early). Thanks!

**Pull request merged**
