### PR TITLE
TINKERPOP3-850: Reduce Graph.addVertex overload ambiguity (v2)

### PR DESCRIPTION
**Pull request by mhfrantz**
https://issues.apache.org/jira/browse/TINKERPOP3-850

Replaces #102 after removing fix for TINKERPOP3-867

### CODE REVIEW

**Comment by mpollmeier** [comment]
I have compiled and run all tests successfully against that version of tinkerpop3. Thumbs up from my side.

Here's the changes I made:
https://github.com/mpollmeier/gremlin-scala/compare/3.1.0-SNAPSHOT

**Comment by mhfrantz** [comment]
Great, thanks @mpollmeier.

Next step, should we have a DISCUSS since this is a breaking change for implementers?

**Comment by mhfrantz** [comment]
TODO: Update the "Upgrade" docs when they are merged to master.

**Comment by okram** [comment]
VOTE +1. 

NOTES: I don't like how many `addVertex()` methods we have now. I don't want our core APIs to be dumping grounds for method permutations (even with `default`) as I would prefer these APIs stay clean and minimalistic (and ultimately, simple for the provider to implement). However, if this is *required* by Scala, then we can add it. If its just a *nicety* for Scala we shouldn't (I leave it up to @mhfrantz to decide). As there will always be a "pretty please" down the line from some other language... We shouldn't cater if the language has a workaround (e.g. how did Gremlin-Scala work prior to this moment?).

**Comment by dkuppitz** [comment]
Since it has been [clarified](https://issues.apache.org/jira/browse/TINKERPOP3-850?focusedCommentId=14955854&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14955854) why the `addVertex(Object[] args)` is needed...
Vote: +1

**Comment by spmallette** [comment]
This is a bit unfair as I only committed the change yesterday and we hadn't discussed procedure completely yet, but this is a breaking change for Graph System Providers and therefore should have appropriate documentation in our new "release docs":

https://github.com/apache/incubator-tinkerpop/blob/master/docs/src/upgrade-release-3.1.x-incubating.asciidoc

I think that PRs should be inclusive of all documentation so that as reviewers we can examine a change in full.  I assume that makes sense to everyone.

@mhfrantz Do you mind amending this PR to include that change?  also, feel free to branch and PR from the apache repo in the future.  no need to do so from a fork since you have commit access.

**Comment by mhfrantz** [comment]
@spmallette I had intended to update the docs after they had been merged, as the TODO earlier in this PR states.  I should be able to get to that today.  Please hold off on merging until then.

Regarding branching from the apache repo, I have been using the fork that my colleagues share so that our project's HipChat notifications show up.

**Comment by spmallette** [comment]
oops - sorry @mhfrantz - didn't notice your NOTE up there. and as for the fork - that's cool too. just wanted to be clear that you were free to just do all that in Apache.

**Comment by okram** [comment]
@mhfrantz -- Can you delete this PR and tell the Gremlin-Scala team our findings? (or am I missing something that we agreed to?)

**Comment by mhfrantz** [comment]
Issue closed as "WON'T FIX", with explanation in the JIRA ticket.

**Pull request closed without merging**
